### PR TITLE
Fix `<Datagrid>` does not show the correct number of selected items

### LINKED ISSUE #11064: "Select All" items in List shows more items selected that total items in the list
I'm using react-admin 5.13.2, and experiencing a weird issue, which looks like a bug. I didn't see this before.

We have a list with 5 items. When we click the checkboxes to select for example 2 items, we see the correct number of selected items on top:

Image

At this point, we click the "Select All" checkbox, and it says that we have 7 items selected, when there are only 5 items in the list:

Image

It seems the 2 items that were previously selected are being counted twice.

### PR DESCRIPTION
**Pull request by djhi**
## Problem

`<Datagrid>` does not show the correct number of selected items when selecting single items first then using the _Select all_ checkbox.

Fixes #11064

## Solution

The condition check in `<DatagridHeader>` was wrong.

## How To Test

- In this PR [Story](https://react-admin-storybook-2luh160y9-marmelab.vercel.app/?path=/story/ra-ui-materialui-list-datagrid--standalone), select a row, then click the header checkbox to select all rows. You should see that 7 items are selected and the _Select all_ button shouldn't appear.
- In production [Story](https://react-admin-storybook-gtmsam0v2-marmelab.vercel.app/?path=/story/ra-ui-materialui-list-datagrid--standalone), do the same. While you won't see the number of selected items because i18n is not setup, note that the _Select all_ button appears. This is because it checks whether the number of selected items is strictly equal to the total number of items. This is a side effect of the bug fixed in this PR.

## Additional Checks

- [x] The PR targets `master` for a bugfix or a documentation fix, or `next` for a feature
- [x] The PR includes **unit tests** (if not possible, describe why)
- [x] The PR includes one or several **stories** (if not possible, describe why)
- [x] The **documentation** is up to date

Also, please make sure to read the [contributing guidelines](https://github.com/marmelab/react-admin#contributing).

### CODE REVIEW

File: packages/ra-ui-materialui/src/list/datagrid/DatagridHeader.tsx [hunk 1]
```diff
@@ -58,11 +58,11 @@ export const DatagridHeader = (props: DatagridHeaderProps) => {
...
-                                  !selectedIds.includes(record.id) &&
-                                  isRowSelectable
-                                      ? isRowSelectable(record)
-                                      : true
+                              .filter(
+                                  record =>
+                                      !selectedIds.includes(record.id) &&
+                                      (!isRowSelectable ||
+                                          isRowSelectable(record))
                               )
```
Comment (djhi) [inline packages/ra-ui-materialui/src/list/datagrid/DatagridHeader.tsx:66]: Another valid fix could be (note the parenthesizes):
```suggestion
                              .filter(
                                  record =>
                                      !selectedIds.includes(record.id) &&
                                      (isRowSelectable
                                          ? isRowSelectable(record)
                                          : true)
                              )
```

**Review by slax57 — APPROVED** [review]
