### PR TITLE
Fix Fab component console warning in empty list small screen

### LINKED ISSUE #4790: Invalid prop passed to Fab component (create button) on empty List
**What you were expecting:**

No console warnings when viewing an empty List **on a small screen**.

**What happened instead:**

Console warning appears:

```
Invalid prop `variant` of value `contained` supplied to `ForwardRef(Fab)`, expected one of ["round","extended"].

```

Screen Shot 2563-05-08 at 10 19 01

**Steps to reproduce:**

View an empty List on small screen and check console.

- Reproduce on demo app by setting one of the resources as an empty array in `examples/simple/src/data.js`

**Environment**

- React-admin version: latest
- React version: any
- Browser: any

### PR DESCRIPTION
**Pull request by cpv123**
Fixes #4790

### CODE REVIEW

File: packages/ra-ui-materialui/src/button/CreateButton.tsx [hunk 1]
```diff
@@ -16,6 +16,7 @@ const CreateButton: FC<CreateButtonProps> = props => {
         classes: classesOverride,
         label = 'ra.action.create',
         icon = defaultIcon,
+        variant = 'text',
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/button/CreateButton.tsx:19]: Why do you add a default value? that's a breaking change. Your code should work without a default value.

Comment (cpv123) [reply packages/ra-ui-materialui/src/button/CreateButton.tsx]: You're right - I've removed default.

**Comment by fzaninotto** [comment]
Thanks!
