### PR TITLE
[RFR] Fix Autocomplete list is cut off by content area

### LINKED ISSUE #2097: Autocomplete list is cut off by content area
bug_autocomplete

**Environment**

* React-admin version: 2.1.4
* React version: 16.3.0
* Browser: Google Chrome 68.0.3440.75

### PR DESCRIPTION
**Pull request by djhi**
Fixes #2097

Before:
Before

After:
After

### CODE REVIEW

File: packages/ra-ui-materialui/src/input/AutocompleteInput.js [hunk 1]
```diff
@@ -272,6 +275,13 @@ export class AutocompleteInput extends React.Component {
 
         const { touched, error, helperText = false } = meta;
 
+        // We need to store the input reference for our Popper element containg the suggestions
+        // but Autosuggest also need this reference (it provides the ref prop)
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.js]: s/also need/also needs/

File: packages/ra-ui-materialui/src/input/AutocompleteInput.js [hunk 2]
```diff
@@ -307,9 +317,14 @@ export class AutocompleteInput extends React.Component {
         const { containerProps, children } = options;
 
         return (
-            <Paper {...containerProps} square>
-                {children}
-            </Paper>
+            <Popper
+                {...containerProps}
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.js]: I think te `containerProps` should be passed to the `Paper` element, otherwise it's a BC break.

File: packages/ra-ui-materialui/src/input/AutocompleteInput.js [hunk 3]
```diff
@@ -307,9 +317,14 @@ export class AutocompleteInput extends React.Component {
...
+                open
+                anchorEl={this.inputEl}
+                placement="bottom-start"
+            >
+                <Paper>{children}</Paper>
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.js]: what happened to the `square` prop?

**Comment by fzaninotto** [comment]
I had to revert this PR as it made the suggestions disappear altogether. So I'm reopening #2097 as it's not fixed.
