### PR TITLE
[Datagrid] Fix non clickable row can't be styled

### LINKED ISSUE #7407: [v4b3] Datagrid row cursor CSS
**What you were expecting:**

I hope for datagrid rows with `rowClick="expand"` but `isRowExpandable` evaluated to falsy does not show a `cursor:pointer` on that row, it should show the default cursor

**What happened instead:**

Currently even if the row is not expandable, there is still a pointer, which is confusing for some of user.
Also there seems is not a good way to override this besides pulling datagrid apart by implementing our own datagrid row logic just for a style change.

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
<Datagrid
        rowClick="expand"
        expand={<Panel />}
        isRowExpandable={(row) => shouldExpand(row)}   // some of rows is not expandable but still shows a cursor: pointer
>
    {children}
</Datagrid>
```

**Other information:**

Although everything conforms to the `sx` documentation for `& .RaDatagrid-clickableRow`, the user experience may not be very good.

I hope we can change how the CSS API `sx` here https://github.com/marmelab/react-admin/blob/next/docs/Datagrid.md?plain=1#L692 to if rowClick is a truthy string or the function evaluated to be truthy

```
<Datagrid
        rowClick={(id, resource, record) => shouldExpand(record) ? "expand" : null}
        expand={<Panel />}
--     /* isRowExpandable={(row) => shouldExpand(row)} */   // we probably even can deprecate the need for this prop
>
    {children}
</Datagrid>
```

This would require us to change this line https://github.com/marmelab/react-admin/blob/next/packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx#L43 `[DatagridClasses.clickableRow]: rowClick`

So we check if `rowClick` is a function and we call the function to see the return value to determine whether this row is clickable.

In this way we will not show a cursor: pointer for non-clickable row.

**Environment**

* React-admin version: v4b3
* Last version that did not exhibit the issue (if applicable):
* React version: 18.0.0-rc.2
* Browser: Edge 99
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by fzaninotto**
We're adding classes to each datagrid row to let developers style them differently whether they're clickable, selectable, expandable, or not. 

Ideally, we should change the cursor by default when a row isn't clickable, selectable, or expandable, but this is for another PR.

Closes #7407

### CODE REVIEW

File: packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx [hunk 1]
```diff
@@ -40,7 +40,6 @@ const DatagridBody: FC<DatagridBodyProps> = React.forwardRef(
                         className: clsx(DatagridClasses.row, {
                             [DatagridClasses.rowEven]: rowIndex % 2 === 0,
                             [DatagridClasses.rowOdd]: rowIndex % 2 !== 0,
-                            [DatagridClasses.clickableRow]: rowClick,
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx:43]: moved to DatagridRow

File: packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx [hunk 2]
```diff
@@ -139,7 +139,12 @@ const DatagridRow: FC<DatagridRowProps> = React.forwardRef((props, ref) => {
         <RecordContextProvider value={record}>
             <TableRow
                 ref={ref}
-                className={className}
+                className={clsx(className, {
+                    [DatagridClasses.expandable]: expandable,
+                    [DatagridClasses.selectable]: selectable,
+                    [DatagridClasses.clickableRow]:
+                        typeof rowClick === 'function' ? false : rowClick,
```
Comment (slax57) [inline packages/ra-ui-materialui/src/list/datagrid/DatagridRow.tsx:146]: I believe this should rather be

```suggestion
                        typeof rowClick === 'function' ? true : rowClick,
```

**Review by slax57 — CHANGES_REQUESTED** [review]

**Review by slax57 — APPROVED** [review]

**Review by WiXSL — APPROVED** [review]
