### PR TITLE
[RFR] Fix error in jsonserver provider on Windows

### LINKED ISSUE #1935: ReferenceError: Buffer is not defined ... in ra-core util fetch.js (running ra on Windows)
First steps from Tutorial (posts list) returns error:

"ReferenceError: Buffer is not defined
    at isValidObject (webpack-internal:///./node_modules/ra-core/lib/util/fetch.js:77:20)
    at Object.flattenObject (webpack-internal:///./node_modules/ra-core/lib/util/fetch.js:87:9)
...
"

**Environment**
* mozilla-neutrino + react preset 
* React-admin version: 2.0.3
* Windows 10

**Solved by:**
`global.Buffer = global.Buffer || require('buffer').Buffer;`

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #1935

### CODE REVIEW

File: packages/ra-core/src/util/fetch.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ const isValidObject = value => {
     }
 
     const isArray = Array.isArray(value);
-    const isBuffer = Buffer.isBuffer(value);
+    const isBuffer = Buffer && Buffer.isBuffer(value);
```
Comment (djhi) [inline packages/ra-core/src/util/fetch.js]: So we won't know if it's a buffer on Windows ?

Comment (fzaninotto) [reply packages/ra-core/src/util/fetch.js]: `Buffer` is a Node object - it does not exist natively in browsers. It's emulated by the `buffer` npm module, which creates a global `Buffer` object. This `buffer` module is required by webpack. So if you use webpack, you don't have the bug. I think the bug appears not if you're on Windows, but if you use another bundler (like rollup). My fix patches that.

But the heart of the problem is that the value cannot be a Buffer since it doesn't make sense for browsers. This test was added in #834, and I validated the PR, but I don't understand this Buffer test anymore.

Comment (alexicum) [reply packages/ra-core/src/util/fetch.js]: Yes, you are right: it's not Windows problem. But neutrino using Webpack too. May be some CRA module setup global Buffer object unlike neutrino.
