### PR TITLE
Fix List bulkActionButtons prop does not handle the value true

### LINKED ISSUE #6925: List bulkActionButtons prop does not handle the value true
**What you were expecting:**
I expect I can pass a boolean to this prop (for example by checking permissions) and it would display the default bulk actions if I pass `true`.

**What happened instead:**
If I pass `true`, no actions are displayed after selecting rows.

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #6925

### CODE REVIEW

File: packages/ra-ui-materialui/src/list/ListView.tsx [hunk 1]
```diff
@@ -68,10 +68,15 @@ export const ListView = (props: ListViewProps) => {
                     })}
                     key={version}
                 >
-                    {bulkActionButtons !== false && bulkActionButtons && (
-                        <BulkActionsToolbar {...controllerProps}>
-                            {bulkActionButtons}
-                        </BulkActionsToolbar>
+                    {bulkActionButtons === true ? (
+                        <DefaultBulkActionButtons />
+                    ) : (
```
Comment (djhi) [inline packages/ra-ui-materialui/src/list/ListView.tsx:73]: I believe `DefaultBulkActionButtons` should be passed as the `BulkActionsToolbar` child

**Review by djhi — CHANGES_REQUESTED** [review]

File: packages/ra-ui-materialui/src/list/ListView.tsx [hunk 2]
```diff
@@ -68,10 +68,17 @@ export const ListView = (props: ListViewProps) => {
...
-                            {bulkActionButtons}
+                            <DefaultBulkActionButtons />
                         </BulkActionsToolbar>
+                    ) : (
+                        bulkActionButtons !== false &&
+                        bulkActionButtons && (
+                            <BulkActionsToolbar {...controllerProps}>
+                                {bulkActionButtons}
+                            </BulkActionsToolbar>
+                        )
```
Comment (djhi) [inline packages/ra-ui-materialui/src/list/ListView.tsx:81]: What do you think about:

```jsx
{bulkActionButtons !== false ? (
    <BulkActionsToolbar {...controllerProps}>
         {isValidElement(bulkActionButtons) ? bulkActionButtons : <DefaultBulkActionButtons />}
    </BulkActionsToolbar>
) : null}
```

Comment (WiXSL) [reply packages/ra-ui-materialui/src/list/ListView.tsx:81]: Even better!

**Review by djhi — APPROVED** [review]
