### PR TITLE
Ensure resource data in redux store is initialized bebfore using it.

### LINKED ISSUE #4196: Custom routes not working when rendering something of the resources (3.1.0)
**What you were expecting:**
A custom route to be able to render the List of a resource

**What happened instead:**
> A client error occurred and your request couldn't be completed.

> Error: An error occurred while selecting the store state: Cannot read property 'list' of undefined.

**Steps to reproduce:**
See the related code. Change path="/posts" to path="/foo" and the error is gone and the posts list is rendered.

**Related code:**
https://codesandbox.io/s/custom-route-not-working-4iyg5

```
import posts from "./posts";

const customRoutes = [
  <Route
    exact
    path="/posts"
    render={props => React.createElement(posts.list, props)}
  />
];

render(
  <Admin
    authProvider={authProvider}
    dataProvider={dataProvider}
    i18nProvider={i18nProvider}
    title="Example Admin"
    customRoutes={customRoutes}
  >
    <Resource name="posts" {...posts} />
  </Admin>,
  document.getElementById("root")
);
```

**Other information:**
On codesandbox you do not actually get the specific error, that I'm seeing here, but that seems cross-origin related, so you can ignore what codesandbox is saying. This is what I'm seeing locally:

> Error: An error occurred while selecting the store state: Cannot read property 'list' of undefined.

A peek at redux state shows me that state.admin.resources is an empty object {} when my function component at /posts is running.

I think somehow the resources are not defined in the redux store quite yet, when a ListController by a customRouted component is trying to read from state.admin.resources.posts.list or something.

**Environment**

* React-admin version: 3.1.0
* Last version that did not exhibit the issue (if applicable): 2.9.x
* React version: 16.12.0
* Browser: Chrome
* Stack trace (in case of a JS error):

> Uncaught Error: An error occurred while selecting the store state: Cannot read property 'list' of undefined.
>     at useSelectorWithStoreAndSubscription (useSelector.js:39)
>     at useSelector (useSelector.js:104)
>     at useListParams (useListParams.js:81)
>     at useListController (useListController.js:54)
>     at List (List.js:80)
>     at renderWithHooks (react-dom.development.js:16260)
>     at mountIndeterminateComponent (react-dom.development.js:18794)
>     at beginWork$1 (react-dom.development.js:20162)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:336)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
>     at invokeGuardedCallback (react-dom.development.js:440)
>     at beginWork$$1 (react-dom.development.js:25780)
>     at performUnitOfWork (react-dom.development.js:24695)
>     at workLoopSync (react-dom.development.js:24671)
>     at performSyncWorkOnRoot (react-dom.development.js:24270)
>     at scheduleUpdateOnFiber (react-dom.development.js:23698)
>     at updateContainer (react-dom.development.js:27103)
>     at react-dom.development.js:27528
>     at unbatchedUpdates (react-dom.development.js:24433)
>     at legacyRenderSubtreeIntoContainer (react-dom.development.js:27527)
>     at Object.render (react-dom.development.js:27608)
>     at Module../src/index.js (index.js:265)
>     ...(bootstrap stuff)

### PR DESCRIPTION
**Pull request by djhi**
Fixes #4196

### CODE REVIEW

File: packages/ra-core/src/controller/useListController.ts [hunk 1]
```diff
@@ -171,7 +171,7 @@ const useListController = (props: ListProps): ListControllerProps => {
         (state: ReduxState) =>
             state.admin.resources[resource]
                 ? state.admin.resources[resource].data
-                : null,
+                : {},
```
Comment (fzaninotto) [inline packages/ra-core/src/controller/useListController.ts]: make it a constant to avoid triggering a new render each time this hook runs.

File: packages/ra-core/src/controller/useListParams.ts [hunk 2]
```diff
@@ -114,7 +114,10 @@ const useListParams = ({
     const history = useHistory();
 
     const { params } = useSelector(
-        (reduxState: ReduxState) => reduxState.admin.resources[resource].list,
+        (reduxState: ReduxState) =>
+            reduxState.admin.resources[resource]
+                ? reduxState.admin.resources[resource].list
+                : {},
```
Comment (fzaninotto) [inline packages/ra-core/src/controller/useListParams.ts]: same

File: packages/ra-core/src/controller/useRecordSelection.ts [hunk 3]
```diff
@@ -14,7 +14,9 @@ const useSelectItems = (resource: string) => {
     const dispatch = useDispatch();
     const selectedIds = useSelector(
         (reduxState: ReduxState) =>
-            reduxState.admin.resources[resource].list.selectedIds,
+            reduxState.admin.resources[resource]
+                ? reduxState.admin.resources[resource].list.selectedIds
+                : [],
```
Comment (fzaninotto) [inline packages/ra-core/src/controller/useRecordSelection.ts]: same

**Comment by djhi** [comment]
> I'm concerned that the useQueryWithStore computes the loaded state by making a difference between undefined and {}. So this change may hide the datagrid skeleton when loading the list the first time

Yes but it does this comparison internally. It has nothing to do with the defaults we specify in the other hooks. Just checked it locally and it works fine
