### PR TITLE
Fix Sidebar component classes

### LINKED ISSUE #4407: Easier customization of Sidebar
It's currently difficult to really customize the styles of the Sidebar component as it does not pass all classes to the underlying Drawer.

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #4407.

I needed to use custom classes and I did it like this.
I you have a better implementation I'm all ears.

### CODE REVIEW

File: packages/ra-ui-materialui/src/layout/Sidebar.js [hunk 1]
```diff
@@ -11,6 +11,18 @@ export const CLOSED_DRAWER_WIDTH = 55;
...
+        paperAnchorLeft: {},
+        paperAnchorRight: {},
+        paperAnchorTop: {},
+        paperAnchorBottom: {},
+        paperAnchorDockedLeft: {},
+        paperAnchorDockedTop: {},
+        paperAnchorDockedRight: {},
+        paperAnchorDockedBottom: {},
+        modal: {},
         drawerPaper: {
```
Comment (Luwangel) [inline packages/ra-ui-materialui/src/layout/Sidebar.js:26]: So now there are no differences between the `drawerPaper` and the `paper` classnames? I think we can use only the `paper` key and mark the `drawerPaper` key as deprecated.

Comment (fzaninotto) [reply packages/ra-ui-materialui/src/layout/Sidebar.js:26]: That's a BC break and it brings small added value. Let's merge this PR as is.

**Comment by fzaninotto** [comment]
Thanks!
