### PR TITLE
Fix create react admin fakerest

### LINKED ISSUE #10493: create-react-admin ignores resource option when using ra-data-fakerest
**What you were expecting:**
Running the following command should bootstrap an Admin with "books" and "authors" resources:

```sh
npx create-react-admin@latest --data-provider ra-data-fakerest --auth-provider none --resource books --resource authors --install npm react-admin-example
```

**What happened instead:**
The Admin is bootstraped with resources "posts" and "comments", ignoring the provided resource options.

**Steps to reproduce:**
Run the above mentioned command.

**Related code:**
Issue comes probably from the following code:

https://github.com/marmelab/react-admin/blob/636469da15fc6266799bb1c843e7565b32fb5a70/packages/create-react-admin/src/app.tsx#L58-L65

**Environment**

* React-admin version: create-react-admin@5.5.3

### PR DESCRIPTION
**Pull request by djhi**
## Problem

Fixes #10493

- `create-react-admin` ignore custom resources when using `ra-data-fakerest`
- The generated `App.tsx` file is incorrectly formatted:
```tsx
import { Admin, Resource, ListGuesser, EditGuesser, ShowGuesser } from 'react-admin';
import { Layout } from './Layout';
import { dataProvider } from './dataProvider';


export const App = () => (
    <Admin
        layout={Layout}
        dataProvider={dataProvider}
        >
        <Resource name="books" list={ListGuesser} edit={EditGuesser} show={ShowGuesser} />
                <Resource name="authors" list={ListGuesser} edit={EditGuesser} show={ShowGuesser} />
    </Admin>
);

    
```

## Solution

- Allow to override resources by specifying them using the CLI `resource` option
- Fix formatting

## How To Test

1. `make build-create-react-admin install`

2. `./node_modules/.bin/create-react-admin myadmin --data-provider ra-data-fakerest --auth-provider local-auth-provider --resource books --resource authors --install skip`
- Check the generated `App.tsx` file contains only the `books` and `authors` resources.
- Check the generated app does not contain an `App.spec.tsx` file
- Check the generated `App.tsx` file is correctly formatted

3. delete the generated app and run `./node_modules/.bin/create-react-admin myadmin --data-provider ra-data-fakerest --auth-provider none --resource books --resource authors --install skip` (no auth)
- Check all the points in 2

4. delete the generated app and run `./node_modules/.bin/create-react-admin myadmin --data-provider ra-data-fakerest --auth-provider none --install skip` (no auth)
- Check the generated `App.tsx` file contains only the `posts` and `comments` resources.
- Check the generated app contains an `App.spec.tsx` file
- Check the generated `App.tsx` file is correctly formatted

## Additional Checks

- [x] The PR targets `master` for a bugfix, or `next` for a feature

### CODE REVIEW

**Review by erwanMarmelab — APPROVED** [review]

File: packages/create-react-admin/src/app.tsx [hunk 1]
```diff
@@ -58,10 +58,6 @@ const stepReducer = (
             const newState = {
                 ...state,
                 dataProvider: action.value,
-                resources:
-                    action.value === 'ra-data-fakerest'
-                        ? ['posts', 'comments']
-                        : state.resources,
```
Comment (slax57) [inline packages/create-react-admin/src/app.tsx:64]: regression: if I don't enter the resources, 'posts' and 'comments' are no longer used automatically

File: packages/create-react-admin/src/generateAppFile.ts [hunk 2]
```diff
@@ -24,24 +24,21 @@ ${
...
-        }>
+        }
+    >
         ${state.resources
             .map(
                 resource =>
                     `<Resource name="${resource}" list={ListGuesser} edit={EditGuesser} show={ShowGuesser} />`
             )
-            .join('\n\t\t')}
+            .join('\n\t')}
```
Comment (slax57) [inline packages/create-react-admin/src/generateAppFile.ts:38]: this made alignment worse according to my tests. The root issue was the use of tabs instead of spaces I believe...

**Review by slax57 — CHANGES_REQUESTED** [review]
