### PR TITLE
Fix BooleanField doesn't show label when used in a Show view

### LINKED ISSUE #6549: BooleanField no longer displays label by default
**What you were expecting:**
When using the `BooleanField` the label should be displayed by default due to the `defaultProps` setting `addLabel` to `true`.

**What happened instead:**
`BooleanField` no longer displays the label without explicitly specifying the `addLabel` prop, this is breaking.

**Steps to reproduce:**
1. Add a `BooleanField` component to a view with the `label` prop set.
2. Observe the field being rendered without the label.
3. Add the `addLabel` prop.
4. Observe the label being rendered.

**Related code:**
https://codesandbox.io/s/eloquent-silence-1te8b

Observe the tick with no label on this page: https://1te8b.sse.codesandbox.io/#/posts/13/show/2

**Other information:**
I think it's down to the memo being moved directly to the default export in this commit: https://github.com/marmelab/react-admin/commit/b79787a65d82da82e3862e7e9c7fadaf82525061#diff-d7c4dd12e78cb28e0370dc53068aa45ec475f6fe54b5b40db238547e6278f5aaR119

It's no longer respecting the `defaultProps`.

**Environment**

* React-admin version: 3.17.3
* Last version that did not exhibit the issue (if applicable): 3.17.2
* React version: 17
* Browser: Chrome
* Stack trace (in case of a JS error): N/A

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #6549

If this is ok, I can do the same for the other fields

### CODE REVIEW

File: packages/ra-ui-materialui/src/field/BooleanField.tsx [hunk 1]
```diff
@@ -27,15 +27,16 @@ const useStyles = makeStyles(
 
 const BooleanField = (props: BooleanFieldProps) => {
     const {
+        addLabel = true,
```
Comment (djhi) [inline packages/ra-ui-materialui/src/field/BooleanField.tsx:30]: I believe this needs to be set on the exported component (the memo)

**Review by djhi — CHANGES_REQUESTED** [review]
Thanks!

File: packages/ra-ui-materialui/src/field/BooleanField.tsx (hunk 1 above)
Comment (WiXSL) [reply packages/ra-ui-materialui/src/field/BooleanField.tsx:30]: Any hint on how to do this since React.memo does not support defaultProps, only the inner component does.

Comment (flouc001) [reply packages/ra-ui-materialui/src/field/BooleanField.tsx:30]: This was how I landed on moving the default logic to the component that clones the component because there didn't appear to be a good way of doing this whilst maintaining the memo.

**Comment by WiXSL** [comment]
Maybe I should revert this changes in Field components until version 4, what do you think?

**Comment by fzaninotto** [comment]
@WiXSL yes, please revert the change you made in the first place that moved the memo call - but please keep the removal of FC!

**Comment by WiXSL** [comment]
> @WiXSL yes, please revert the change you made in the first place that moved the memo call - but please keep the removal of FC!

@fzaninotto, the prblem is that i get `TS2339: Property 'propTypes' does not exist on type 'NamedExoticComponent '.` error on `defaultProps` and `propTypes`

**Comment by fzaninotto** [comment]
does @ts-ignore work?

**Comment by WiXSL** [comment]
> does @ts-ignore work?

Sorry, yes, It seems to work

**Comment by fzaninotto** [comment]
Suprseded by #6564

**Review by fzaninotto — APPROVED** [review]
