### PR TITLE
Fix Create generic record type

### LINKED ISSUE #8921: The "id" field for the RaRecord type at Create makes no sense
**What you were expecting:**
I do not expect an error because my request in the body does not require an id

**What happened instead:**
I'm getting a "TS2344: Type 'MyTypeDto' does not satisfy the constraint 'RaRecord'.   Property 'id' is missing in type 'MyTypeDto' but required in type 'RaRecord'" error

**Steps to reproduce:**
Add a type without an "id" field and pass in the generic type for the Create component

**Related code:**
```
import { Create } from 'react-admin';

type MyTypeDto = {
  name: string;
  someKey: string;
};

export default function CreateDetails() {
  return (
    <Create<MyTypeDto> title="Add Details" resource="send-to">
      ...
    </Create>
  );
}
```

**Environment**

* React-admin version: 4.9.0
* React version: 18.2.0
* Stack trace (in case of a JS error): TS types.d.ts(9, 5): 'id' is declared here.

### PR DESCRIPTION
**Pull request by djhi**
Fixes #8921

### CODE REVIEW

File: packages/ra-core/src/types.ts [hunk 1]
```diff
@@ -209,7 +209,7 @@ export interface CreateParams<T = any> {
     data: T;
     meta?: any;
 }
-export interface CreateResult<RecordType extends RaRecord = any> {
+export interface CreateResult<RecordType extends Omit<RaRecord, 'id'> = any> {
```
Comment (slax57) [inline packages/ra-core/src/types.ts:212]: I believe that `CreateResult` should still require an `id`

File: packages/ra-core/src/controller/create/CreateBase.tsx [hunk 2]
```diff
@@ -37,11 +37,20 @@ import { ResourceContextProvider } from '../../core';
...
     children,
     ...props
-}: CreateControllerProps<RecordType> & { children: ReactNode }) => {
-    const controllerProps = useCreateController<RecordType>(props);
+}: CreateControllerProps<RecordType, Error, ResultRecordType> & {
+    children: ReactNode;
+}) => {
+    const controllerProps = useCreateController<
+        RecordType,
+        Error,
```
Comment (slax57) [inline packages/ra-core/src/controller/create/CreateBase.tsx:51]: why not set this to `unknown` instead of `Error`?

Comment (djhi) [reply packages/ra-core/src/controller/create/CreateBase.tsx:51]: Ideally we should accept an Error generic parameter in CreateBase too. I figured it would be more convenient to have a default Error

**Review by slax57 — APPROVED** [review]
