### PR TITLE
Fix Warn about unsaved changes when modifying CheckGroupInput and ArrayInput

### LINKED ISSUE #6939: Warn about unsaved changes when modifying `CheckGroupInput` and `ArrayInput`
This problem was fixed in #5776 (`v3.11.3`) and is back since version `3.19.1`
You can reproduce it editing a Post record in the simple example, modifying one of these controls and trying to submit the form.

I'll try to see exactly what the issue is.

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #6939

### CODE REVIEW

File: packages/ra-core/src/form/useWarnWhenUnsavedChanges.tsx [hunk 1]
```diff
@@ -28,7 +28,7 @@ const useWarnWhenUnsavedChanges = (
         }
 
         const release = history.block(location => {
-            const isInsideForm = location.pathname.startsWith(
+            const isInsideForm = history.location.pathname.startsWith(
```
Comment (WiXSL) [inline packages/ra-core/src/form/useWarnWhenUnsavedChanges.tsx:31]: The problem is that `location.pathname` is pointing to the wrong path, so I use `history.location.pathname`.
I have no clue why this happens

Comment (WiXSL) [inline packages/ra-core/src/form/useWarnWhenUnsavedChanges.tsx:31]: This is wrong, I'm removing the feature
