### PR TITLE
Fix Notification undo button's color on success type

### LINKED ISSUE #6173: Undo link color on success notification
**What you were expecting:**
Using the new "success" notification type, the notification is turned green. The undo link is still the primary color of the theme, which by default is blue. I would expect the link color to match the green notification color, such as [green 900 (#1b5e20)](https://material-ui.com/customization/color/).

**What happened instead:**
image

**Steps to reproduce:**
`notify("resources.employee.updated", "success", {}, true)`

**Environment**
* React-admin version: 3.14.3
* React version: 17.0.2
* Browser: Chrome Version 90.0.4430.72 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by WiXSL**
Closes #6173

### CODE REVIEW

File: packages/ra-ui-materialui/src/layout/Notification.tsx [hunk 1]
```diff
@@ -34,9 +34,12 @@ const useStyles = makeStyles(
             backgroundColor: theme.palette.error.light,
             color: theme.palette.error.contrastText,
         },
-        undo: {
-            color: theme.palette.primary.light,
-        },
+        undo: (props: Props & Omit<SnackbarProps, 'open'>) => ({
+            color:
+                props.type === 'success'
+                    ? theme.palette[props.type].contrastText
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/layout/Notification.tsx:40]:
```suggestion
                    ? theme.palette.success.contrastText
```

**Review by fzaninotto — CHANGES_REQUESTED** [review]

**Review by fzaninotto — APPROVED** [review]

**Comment by fzaninotto** [comment]
Thanks!
