### PR TITLE
fix ra-data-graphql-simple convert SCALAR Date type to ISOString

### LINKED ISSUE #4218: DateTimeInput converts to empty Object in ra-data-graphql-simple provider
**What you were expecting:**
Dateinput should return the correct datetime string

**What happened instead:**
Variables that are connected to this input are {} in graphql mutation

**Steps to reproduce:**
Install ra-data-graphql-simple use any form that contains DateTimeInput and submit, network inspect the graphql request

* React-admin version:"^3.1.1"
* Last version that did not exhibit the issue (if applicable):
* React version: "^16.12.0"
* Browser: Chrome
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by ThieryMichel**
fix #4218

### CODE REVIEW

File: packages/ra-data-graphql-simple/src/buildVariables.js [hunk 1]
```diff
@@ -35,6 +35,9 @@ const castType = (value, type) => {
         case 'SCALAR:Boolean':
             return Boolean(value);
 
+        case 'SCALAR:Date':
```
Comment (djhi) [inline packages/ra-data-graphql-simple/src/buildVariables.js]: Are you aware that people might name this scalar whatever they want? It is not supported out of the box by GraphQL and might be named `DateTime`, `IsoDate` or `Smurf` for what we know. I think this should be documented that this **example** implementation of a graphql data provider expect it to be named `Date` and be an ISO date.

Comment (ThieryMichel) [reply packages/ra-data-graphql-simple/src/buildVariables.js]: Maybe my fix is not good then. We need to serialize date object to ISO to construct the query. Otherwise it get serialized to {} and the info is lost.
