### PR TITLE
Fix null values cause warning in forms

### LINKED ISSUE #7782: Warning when using null value on TextInput
**What you were expecting:**

When my API returns `null` as the value for a `<TextInput />`, it should not lead to any warnings.

**What happened instead:**

When a record is returned by the API with a value of `null`, this leads to a warning when used on a text input:

> Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.

and 

> Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.

**Steps to reproduce:**

1. Go to the sandbox provided
2. Open any post to edit
3. Observe console output (you may need to filter for `should not be null`)

**Related code:**

https://codesandbox.io/s/hopeful-worker-u1dxlq?file=/src/posts/PostEdit.tsx

**Other information:**

- Setting the `defaultValue` of the input, or `defaultValues` of the form to an empty string (`''`), doesn't make the warning go away
- From the migration docs it's clear that the behaviour changed in regard of how `null` values are treated by react-form-hook compared to react-final-form. But it's unclear to me how to mitigate this warning.

**Environment**

* React-admin version: 4.1.2
* Last version that did not exhibit the issue (if applicable): 3.19.x
* React version: 17

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #7782

### CODE REVIEW

File: packages/ra-core/src/form/getFormInitialValues.ts [hunk 1]
```diff
@@ -10,6 +10,12 @@ export default function getFormInitialValues(
         getValues(defaultValues, record),
         record
     );
+    // replace null values by empty string to avoid controlled/ uncontrolled input warning
+    Object.keys(finalInitialValues).forEach(key => {
+        if (finalInitialValues[key] === null) {
+            finalInitialValues[key] = '';
+        }
+    });
```
Comment (slax57) [inline packages/ra-core/src/form/getFormInitialValues.ts:18]: This doesn't work for nested values, like `author.name` for instance

**Review by slax57 — CHANGES_REQUESTED** [review]

**Review by WiXSL — APPROVED** [review]
Apart from @slax57 review seems good!

File: packages/ra-core/src/form/getFormInitialValues.ts (hunk 1 above)
Comment (fzaninotto) [reply packages/ra-core/src/form/getFormInitialValues.ts:18]: So the fix requires a bit of recursion: 

```jsx
export default function getFormInitialValues(
    defaultValues: DefaultValue,
    record?: Partial<RaRecord>
) {
    const finalInitialValues = merge(
        {},
        getValues(defaultValues, record),
        record
    );
    // replace null values by empty string to avoid controlled/ uncontrolled input warning
    return mapValuesDeep(finalInitialValues, value =>
        value === null ? '' : value
    );
}

const mapValuesDeep = (obj, callback) =>
    mapValues(obj, v =>
        isPlainObject(v) ? mapValuesDeep(v, callback) : callback(v)
    );
```

But I'm afraid it could have nasty side effects. Why should we modify the inner properties of embedded objects - some of which my not be modifiable? Besides, the `sanitizeEmptyValues` doesn't work for nested properties, so the empty string would be sent back to the server. 

All in all, this is another corner case, which already exists today, and I don't think this PR makes it worse.

**Review by slax57 — APPROVED** [review]
