### PR TITLE
Fix refresh button breaks useGetList result with application cache

### LINKED ISSUE #4817: No data from useGetList after refresh
**What you were expecting:**

useGetList gives data even after pressing refresh button at the header toolbar

**What happened instead:**

Data is empty after refresh

**Steps to reproduce:**

Reproduces at  the simple example `examples/simple/src/customRouetLayout.js`.

1. `make run-simple`
2. Go to http://localhost:8080/#/custom2
3. "Found 13 posts!" displayed.
4. Press Refresh icon
5. "Found posts!" displayed. (no posts listed.)

**Other information:**

Passing version value of `useVersion()` hook to options parameter of `useGetList` seems to be a workaround.
```js
--- a/examples/simple/src/customRouteLayout.js
+++ b/examples/simple/src/customRouteLayout.js
@@ -1,12 +1,15 @@
 import React from 'react';
-import { useGetList, useAuthenticated, Title } from 'react-admin';
+import { useGetList, useAuthenticated, Title, useVersion } from 'react-admin';
 
 const CustomRouteLayout = () => {
     useAuthenticated();
+    const version = useVersion();
     const { ids, data, total, loaded } = useGetList(
         'posts',
         { page: 1, perPage: 10 },
-        { field: 'published_at', order: 'DESC' }
+        { field: 'published_at', order: 'DESC' },
+        {},
+        { version }
     );
```

**Environment**

* React-admin version: current master branch 70e9b48
* Browser: Chrome

### PR DESCRIPTION
**Pull request by fzaninotto**
Fixes #4817

### CODE REVIEW

File: packages/ra-core/src/dataProvider/useQueryWithStore.ts [hunk 1]
```diff
@@ -120,7 +121,8 @@ const useQueryWithStore = (
     loaded: boolean;
 } => {
     const { type, resource, payload } = query;
-    const requestSignature = JSON.stringify({ query, options });
+    const version = useVersion(); // used to allow force reload
```
Comment (fzaninotto) [inline packages/ra-core/src/dataProvider/useQueryWithStore.ts:124]: Now even if the caller forgets to pass the version in the query options, the side effect will re-execute when a REFRESH_VIEW action is dispatched.
