### PR TITLE
Fix delete contexts don't send mutation `meta`

### LINKED ISSUE #8016: meta is undefined in params of delete method of dataProvider when using DeleteButton
**What you were expecting:**

Receiving `meta` in data provider when using DeleteButton with `mutationOptions` prop.

**What happened instead:**

`meta` is undefined in the `delete` method of `dataProvider`.

**Steps to reproduce:**

1. Open [my fork of code sandbox](https://codesandbox.io/s/young-pond-nioyun?file=/src/users/UserEdit.tsx:613-683), logout and login with "user" and "password"
2. Navigate to Users, pick one and enter to Edit page
3. Click on the Delete button
4. Check the console

**Related code:**

https://codesandbox.io/s/young-pond-nioyun?file=/src/users/UserEdit.tsx:613-683

```js
// UserEdit.tsx line 34
<DeleteWithConfirmButton mutationOptions={{ meta: { foo: "bar" } }} />
```

```js
// dataProvider.tsx line 47
delete: (resource, params) => {
    // HERE
    console.log("No meta :(", { params });
    return dataProvider.delete(resource, params);
  }
```

**Other information:**

image
image

Suggestion to possible fix:
https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx#L98
```js
// ra-core/src/controller/button/useDeleteWithConfirmController.tsx line 98
// ra-core/src/controller/button/useDeleteWithUndoController.tsx line 66

// from
{ id: record.id, previousData: record }
// to
{ id: record.id, previousData: record, meta: mutationOptions.meta }
```
image

**Environment**

* React-admin version: 4.2.4
* Last version that did not exhibit the issue (if applicable):
* React version: 17
* Browser: Chrome 100+
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by septentrion-730n**
Fix #8016
Kudos to @carlos-duran

- [x] Fix delete contexts don't send mutation meta
- [x] Fix settings `mutationOptions` on `<BulkDeleteWithConfirmButton>`and `<BulkDeleteWithUndoButton>` generates an error
- [x] Add `mutationOptions` prop description on delete buttons documentation

[useMutation documentation](https://react-query-v3.tanstack.com/reference/useMutation).

### CODE REVIEW

File: packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx [hunk 1]
```diff
@@ -95,7 +95,11 @@ const useDeleteWithConfirmController = <RecordType extends RaRecord = any>(
             event.stopPropagation();
             deleteOne(
                 resource,
-                { id: record.id, previousData: record },
+                {
+                    id: record.id,
+                    previousData: record,
+                    meta: mutationOptions?.meta,
```
Comment (fzaninotto) [inline packages/ra-core/src/controller/button/useDeleteWithConfirmController.tsx:101]: You should destructure mutationOptions earlier, otherwise when you pass them line 134, they may include the `meta` prop that react-query doesn't expect. I'm surprised TypeScript lets you dit it. 

So earlier, you should do as in `useEditController`:

https://github.com/marmelab/react-admin/blob/9b028c1e0c9ace57630530f6bfbfd0392f3031a1/packages/ra-core/src/controller/edit/useEditController.ts#L65

File: packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx [hunk 2]
```diff
@@ -63,7 +63,11 @@ const useDeleteWithUndoController = <RecordType extends RaRecord = any>(
             event.stopPropagation();
             deleteOne(
                 resource,
-                { id: record.id, previousData: record },
+                {
+                    id: record.id,
+                    previousData: record,
+                    meta: mutationOptions?.meta,
```
Comment (fzaninotto) [inline packages/ra-core/src/controller/button/useDeleteWithUndoController.tsx:69]: same remark

File: packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx [hunk 3]
```diff
@@ -41,7 +45,7 @@ export const BulkDeleteWithConfirmButton = (
     const translate = useTranslate();
     const [deleteMany, { isLoading }] = useDeleteMany(
         resource,
-        { ids: selectedIds },
+        { ids: selectedIds, meta: mutationOptions?.meta },
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx:48]: same

File: packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx [hunk 4]
```diff
@@ -141,13 +145,20 @@ const sanitizeRestProps = ({
...
+export interface BulkDeleteWithConfirmButtonProps<
+    RecordType extends RaRecord = any,
+    MutationOptionsError = unknown
+> extends BulkActionProps,
         ButtonProps {
     confirmContent?: React.ReactNode;
     confirmTitle?: string;
     icon?: ReactElement;
     mutationMode: MutationMode;
+    mutationOptions?: UseMutationOptions<
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx:157]: the type is incorrect. This type doesn't contain `meta`. use `useEditController` as an inspiration instead.

https://github.com/marmelab/react-admin/blob/9b028c1e0c9ace57630530f6bfbfd0392f3031a1/packages/ra-core/src/controller/edit/useEditController.ts#L230-L234

File: packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx [hunk 5]
```diff
@@ -36,7 +40,7 @@ export const BulkDeleteWithUndoButton = (
     const handleClick = e => {
         deleteMany(
             resource,
-            { ids: selectedIds },
+            { ids: selectedIds, meta: mutationOptions?.meta },
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx:43]: same

File: packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx [hunk 6]
```diff
@@ -95,10 +99,17 @@ const sanitizeRestProps = ({
...
 
-export interface BulkDeleteWithUndoButtonProps
-    extends BulkActionProps,
+export interface BulkDeleteWithUndoButtonProps<
+    RecordType extends RaRecord = any,
+    MutationOptionsError = unknown
+> extends BulkActionProps,
         ButtonProps {
     icon?: ReactElement;
+    mutationOptions?: UseMutationOptions<
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/button/BulkDeleteWithUndoButton.tsx:108]: and same

File: docs/Buttons.md [hunk 7]
```diff
@@ -244,11 +244,11 @@ export const PostList = () => (
...
-| Prop         | Required | Type            | Default            | Description                         |
-| ------------ | -------- | --------------- | ------------------ | ----------------------------------- |
-| `label`      | Optional | `string`        | 'ra.action.delete' | label or translation message to use |
-| `icon`       | Optional | `ReactElement`  | `<DeleteIcon>`     | iconElement, e.g. `<CommentIcon />` |
-| `exporter`   | Optional | `Function`      | -                  | Override the List exporter function |
+| Prop                | Required | Type            | Default            | Description                                        |
+| --------------------| -------- | --------------- | ------------------ | ---------------------------------------------------|
+| `label`             | Optional | `string`        | 'ra.action.delete' | label or translation message to use                |
+| `icon`              | Optional | `ReactElement`  | `<DeleteIcon>`     | iconElement, e.g. `<CommentIcon />`                |
+| `mutationOptions`   | Optional | `object`        | null               | options for react-query `useMutation` hook         |
```
Comment (fzaninotto) [inline docs/Buttons.md:251]: The description isn't entirely accurate, as react-query's `options` cannot contain a `meta` key. In fact, you should probably add an example explaining how to set the `meta` parameter.

File: docs/Buttons.md [hunk 8]
```diff
@@ -277,6 +277,7 @@ Delete the current record after a confirm dialog has been accepted. To be used i
 | `confirmContent`                                           | Optional | `ReactNode`                      | 'ra.message.delete_content' | Message or React component to be used as the body of the confirm dialog |
 | `redirect`                                                 | Optional | `string | false | Function`      | 'list'                      | Custom redirection after success side effect                            |
 | `translateOptions`                                         | Optional | `{ id?: string, name?: string }` | {}                          | Custom id and name to be used in the confirm dialog's title             |
+| `mutationOptions`                                          | Optional |                                  | null                        | options for react-query `useMutation` hook                              |
```
Comment (fzaninotto) [inline docs/Buttons.md:280]: same

**Review by fzaninotto — CHANGES_REQUESTED** [review]

**Comment by fzaninotto** [comment]
Could you add a test to prove that it works?

File: docs/Buttons.md (hunk 7 above)
Comment (djhi) [reply docs/Buttons.md:251]: There is a `meta` option in `useMutation`. It is of type `Record<string, unknown>` when ours is `any` though.

**Comment by septentrion-730n** [comment]
> Could you add a test to prove that it works?

Here you are, colleague of little faith.

File: packages/ra-core/src/controller/button/useDeleteWithUndoController.spec.tsx [hunk 9]
```diff
@@ -0,0 +1,49 @@
...
+            <MemoryRouter>
+                <CoreAdminContext dataProvider={dataProvider}>
+                    <Routes>
+                        <Route path="/" element={<MockComponent />} />
+                    </Routes>
+                </CoreAdminContext>
+            </MemoryRouter>
+        );
+
+        await screen.getByText('Delete');
```
Comment (fzaninotto) [inline packages/ra-core/src/controller/button/useDeleteWithUndoController.spec.tsx:43]: same

**Review by fzaninotto — CHANGES_REQUESTED** [review]

File: packages/ra-core/src/controller/button/useDeleteWithConfirmController.spec.tsx [hunk 10]
```diff
@@ -0,0 +1,49 @@
...
+                    <Routes>
+                        <Route path="/" element={<MockComponent />} />
+                    </Routes>
+                </CoreAdminContext>
+            </MemoryRouter>
+        );
+
+        await screen.getByText('Delete');
+        fireEvent.click(screen.getByText('Delete'));
+        waitFor(() => expect(receivedMeta).toEqual('metadata'), {
```
[the remark this answers is not in the document]
Comment (fzaninotto) [reply packages/ra-core/src/controller/button/useDeleteWithConfirmController.spec.tsx:44]: My bad: handleDelete doesn't have anything to do with the confirmation.

**Review by fzaninotto — APPROVED** [review]
