### PR TITLE
Fix List Filter Menu is not accessible

### LINKED ISSUE #6964: List Filter Menu is not accessible
**What you were expecting:**
I expect using the keyboard to open the filter menu and select an item to work

**What happened instead:**
I can use the keyboard to open the filter menu but not to select one of its items

**Steps to reproduce:**
Open the [demo](https://marmelab.com/react-admin-demo/#/commands) and use the keyboard to focus the filter menu and try to select an item.

**Environment**

* React-admin version: 3.19.3
* Last version that did not exhibit the issue (if applicable):
* React version: 17

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #6964

### CODE REVIEW

File: packages/ra-ui-materialui/src/list/filter/FilterButton.tsx [hunk 1]
```diff
@@ -91,12 +91,13 @@ const FilterButton = (props: FilterButtonProps): JSX.Element => {
...
                 onClose={handleRequestClose}
             >
-                {hiddenFilters.map((filterElement: JSX.Element) => (
+                {hiddenFilters.map((filterElement: JSX.Element, index) => (
                     <FilterButtonMenuItem
                         key={filterElement.props.source}
                         filter={filterElement}
                         resource={resource}
                         onShow={handleShow}
+                        autoFocus={index === 0}
```
Comment (djhi) [inline packages/ra-ui-materialui/src/list/filter/FilterButton.tsx:100]: I don't get why this is necessary to fix the keyboard navigation. Can you explain?

**Review by djhi — COMMENTED** [review]
While you're on this file, would you mind adding the missing `aria-haspopup="true"` on the `Button` element?

File: packages/ra-ui-materialui/src/list/filter/FilterButton.tsx (hunk 1 above)
Comment (WiXSL) [reply packages/ra-ui-materialui/src/list/filter/FilterButton.tsx:100]: I couldn't get it to work otherwise, I'm forcing the focus on the first menu item, do you have a suggestion with aria attributes?

Comment (djhi) [reply packages/ra-ui-materialui/src/list/filter/FilterButton.tsx:100]: No but I fail to find a difference between our code and the MUI v4 demos for the menu

Comment (WiXSL) [reply packages/ra-ui-materialui/src/list/filter/FilterButton.tsx:101]: > No but I fail to find a difference between our code and the MUI v4 demos for the menu

What I've noticed is that they don't have a forwardRef `MenuItem` inside a `Menu` in their examples.
It works out of the box without this, but of course, we need it.

Comment (WiXSL) [reply packages/ra-ui-materialui/src/list/filter/FilterButton.tsx:101]: For example, this works:

```jsx
<Menu
    open={open}
    anchorEl={anchorEl.current}
    onClose={handleRequestClose}
>
    {hiddenFilters.map((filterElement: JSX.Element, index) => (
        <MenuItem
            key={filterElement.props.source}
            //filter={filterElement}
            //resource={resource}
            //onShow={handleShow}
            //autoFocus={index === 0}
        >
            <FieldTitle
                label={filterElement.props.label}
                source={filterElement.props.source}
                resource={resource}
            />
        </MenuItem>
    ))}
</Menu>

Comment (WiXSL) [reply packages/ra-ui-materialui/src/list/filter/FilterButton.tsx:101]: Of course it would be a BC

**Review by fzaninotto — APPROVED** [review]
