### PR TITLE
Make `<TabbedForm tabs>` use the `onChange` prop

### LINKED ISSUE #10532: TabbedForm: I cannot get the tabindex somehow when I click on the tabs
**What you were expecting:**
`TabbedForm` onChange logic does not seem to work, so that I can get the current tabIndex (unless there is another way to achieve this)

**What happened instead:**
The `onChange` function is not triggered

**Steps to reproduce:**
This is how I have the logic setup:

```
    <TabbedForm
      sanitizeEmptyValues
      defaultValues={getDefaultValues({})}
      tabs={
        <TabbedFormTabs
          onChange={(tabIndex) => {
            console.log('log1-tabIndex2', tabIndex);
            setActiveTab(tabIndex);
          }}
        />
      }
    >
// ... more code here, with tabs, etc.
```

I believe the `onChange` will never be triggered, because you override this with a specific `handleChange` function which does not have a `onChange()` call at the end:

Image

**Environment**

* React-admin version: "^5.2.1"
* Last version that did not exhibit the issue (if applicable):
* React version: "^18.3.1"
* Browser: N/A
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by erwanMarmelab**
Fixes #10532

### CODE REVIEW

File: packages/ra-ui-materialui/src/form/TabbedFormView.tsx [hunk 1]
```diff
@@ -37,6 +37,9 @@ export const TabbedFormView = (props: TabbedFormViewProps): ReactElement => {
         if (!syncWithLocation) {
             setTabValue(value);
         }
+        if (tabs.props.onChange) {
```
Comment (djhi) [inline packages/ra-ui-materialui/src/form/TabbedFormView.tsx:40]: We really should rewrite this component with contexts.

**Review by djhi — APPROVED** [review]
