### PR TITLE
Fix AutocompleteInput input's value not updating correctly

### LINKED ISSUE #8227: `AutocompleteInput` input's value not updating correctly
Manipulating the `AutocompeteInput`'s value by the user may lead to not removable characters until focus is lost

https://user-images.githubusercontent.com/8268610/193594861-53241eed-552a-4f0b-84ed-9ec804c59775.mov

Environment

React-admin version: 4.4.0
Last version that did not exhibit the issue (if applicable):
React version: 18.2.0
Browser: Chrome
Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #8227

### CODE REVIEW

File: packages/ra-ui-materialui/src/input/AutocompleteInput.tsx [hunk 1]
```diff
@@ -440,10 +452,12 @@ If you provided a React element for the optionText prop, you must also provide t
             }
 
             return eventType && eventType === 'change'
-                ? selectedItemTexts.includes(filter) && selectedChoice
+                ? selectedItemTexts.includes(filter) &&
+                      selectedChoice &&
+                      selectedChoice[optionValue || 'id'] !== emptyValue
```
Comment (slax57) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.tsx:457]: Not sure this will work in the `multiple` case, because int this case `selectedChoice` seems to be an array (see line 447)

**Review by slax57 — CHANGES_REQUESTED** [review]
Besides, it would be nice if you could add some tests to cover this case in the future :slightly_smiling_face:

File: packages/ra-ui-materialui/src/input/AutocompleteInput.tsx (hunk 1 above)
Comment (WiXSL) [reply packages/ra-ui-materialui/src/input/AutocompleteInput.tsx]: Doesn't seems to be a problem for multiple, so I'll just make that evaluation when is not multiple

**Comment by slax57** [comment]
I'm afraid the fix is still incomplete.

There are still cases where you cannot use backspace, for example in the `AutocompleteInput/Basic` story:

Peek 07-10-2022 18-47

I think the problem actually comes from this function:

```tsx
    const handleInputChange = (
        event: any,
        newInputValue: string,
        reason: string
    ) => {
        if (!doesQueryMatchSelection(newInputValue, event?.type)) {
            setFilterValue(newInputValue);
            debouncedSetFilter(newInputValue);
        }
    };
```

The `if` makes it so that the input is not updated if the new value is a valid option.
I don't know why this `if` was added. I tried removing it and everything seems to work just fine without it.

Besides, the unit test `should allow to clear the first character` is actually wrong.
Actually it should break from what I see in the storybook.
I believe it's because after focus, `userEvent.type(input, 'f');` is actually **replacing** the whole text content instead of appending to it.
We should fix this test, too.

In the end, I'm not sure we need to change the `doesQueryMatchSelection` callback. Removing the `if` in `handleInputChange` seems to be enough.

File: packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx [hunk 2]
```diff
@@ -58,6 +58,43 @@ describe('<AutocompleteInput />', () => {
         expect(screen.queryByDisplayValue('foo')).not.toBeNull();
     });
 
+    it('should allow filter to match the selected choice while removing characters in the input', async () => {
```
Comment (slax57) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx:61]: This new test seems fine, but why did you remove the old one testing the emptyValue case? To me we should keep both.

Besides, if my understanding is correct, this test supersedes the `should allow to clear the first character` test, which is useless anyway, so we should remove it IMO.

File: packages/ra-ui-materialui/src/input/AutocompleteInput.tsx [hunk 3]
```diff
@@ -429,21 +441,29 @@ If you provided a React element for the optionText prop, you must also provide t
...
+                    selectedChoice[
+                        typeof optionText === 'string' ? optionText : 'name'
+                    ] === filter;
             }
 
             return eventType && eventType === 'change'
-                ? selectedItemTexts.includes(filter) && selectedChoice
+                ? selectedItemTexts.includes(filter) &&
+                      selectedChoice &&
+                      !isValidChoice
```
Comment (slax57) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.tsx:463]: I am a bit skeptical about having a `doesQueryMatchSelection` function return `false` when the choice is a valid one.

From the tests, your fix is clearly working, I'm not questioning that, but I still have the feeling we put a patch at the wrong place.
What is the purpose of this `doesQueryMatchSelection` function anyway?
To me it is very unclear what it's supposed to do, so it's difficult to tell if its implementation is correct or not.
Did you figure it out?

**Review by slax57 — CHANGES_REQUESTED** [review]

File: packages/ra-ui-materialui/src/input/AutocompleteInput.tsx (hunk 3 above)
Comment (WiXSL) [reply packages/ra-ui-materialui/src/input/AutocompleteInput.tsx:463]: Let me research a little bit, at first, removing it makes some tests fails.

File: packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx (hunk 2 above)
Comment (WiXSL) [reply packages/ra-ui-materialui/src/input/AutocompleteInput.spec.tsx:61]: You're actually right!

File: packages/ra-ui-materialui/src/input/AutocompleteInput.tsx (hunk 3 above)
Comment (slax57) [reply packages/ra-ui-materialui/src/input/AutocompleteInput.tsx:463]: The more I think about it the more I think it's wrong :sweat_smile: 

Actually, putting the `multiple` case aside: 
- `selectedItemTexts` is equal to `[getOptionLabel(selectedChoice)]` so `selectedItemTexts.includes(filter)` is basically equivalent to `getOptionLabel(selectedChoice) === filter`
- `isValidChoice` is, after simplification, equal to `selectedChoice[optionText] === filter`, which is very very similar to `getOptionLabel(selectedChoice) === filter`

So in the end, `selectedItemTexts.includes(filter) && !isValidChoice` will probably always be `false`. We are basically expecting something and its opposite to be `true` at the same time.

Comment (WiXSL) [reply packages/ra-ui-materialui/src/input/AutocompleteInput.tsx]: When you are right, you are right! 😄

Comment (WiXSL) [reply packages/ra-ui-materialui/src/input/AutocompleteInput.tsx]: I simplify everything to always run the filter on input change, and call `doesQueryMatchSelection` on anything else

File: packages/ra-ui-materialui/src/input/AutocompleteInput.tsx [hunk 4]
```diff
@@ -422,15 +434,18 @@ If you provided a React element for the optionText prop, you must also provide t
         newInputValue: string,
         reason: string
     ) => {
-        if (!doesQueryMatchSelection(newInputValue, event?.type)) {
+        if (
+            event?.type === 'change' ||
+            !doesQueryMatchSelection(newInputValue, event?.type)
```
Comment (slax57) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.tsx:439]: We no longer need to check the `event` type in `doesQueryMatchSelection()`, because it's already done in `handleInputChange()`.

`handleInputChange()` was the only place where  `doesQueryMatchSelection()` was called with a second parameter, so we can safely remove it IMO.

File: packages/ra-ui-materialui/src/input/AutocompleteInput.tsx [hunk 5]
```diff
@@ -444,7 +459,7 @@ If you provided a React element for the optionText prop, you must also provide t
                 ? selectedItemTexts.includes(filter) && selectedChoice
                 : selectedItemTexts.includes(filter);
         },
-        [getOptionLabel, multiple, selectedChoice]
+        [getOptionLabel, multiple, optionText, selectedChoice]
```
Comment (slax57) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.tsx:462]: linter warning here

**Review by slax57 — CHANGES_REQUESTED** [review]

**Review by slax57 — APPROVED** [review]
