### PR TITLE
Fix bad url upon `<FilterLiveSearch>` submission

### LINKED ISSUE #9387: FilterLiveSearch input with "Enter" keyboard causes wrong url
**What you were expecting:**
FilterLiveSearch input with "Enter" keyboard should have correct url  [https://marmelab.com/react-admin-demo/#/customers?q=test](https://marmelab.com/react-admin-demo/#/customers?q=test)

**What happened instead:**
FilterLiveSearch input with "Enter" keyboard cause wrong url

**Steps to reproduce:**
1. Go to [https://marmelab.com/react-admin-demo/#/customers](https://marmelab.com/react-admin-demo/#/customers)
2. Type any thing inside "Search input"
3. Press "Enter"
4. Observe the url: [https://marmelab.com/react-admin-demo/?q=test#/customers?filter=%7B%22q%22%3A%22test%22%7D&order=DESC&page=1&perPage=25&sort=last_seen](https://marmelab.com/react-admin-demo/?q=test#/customers?filter=%7B%22q%22%3A%22test%22%7D&order=DESC&page=1&perPage=25&sort=last_seen)

**Related code:**
 [https://marmelab.com/react-admin-demo/#/customers](https://marmelab.com/react-admin-demo/#/customers)

**Environment**

* React-admin version: 4.12.0
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Chrome Version 118.0.5993.89 (Official Build) (64-bit)
* Stack trace (in case of a JS error): N/A

### PR DESCRIPTION
**Pull request by erwanMarmelab**
## Problem
FilterLiveSearch input with "Enter" keyboard event change url from `myUrl/#/myTab?filter={"q"%3A"test"}` to `myUrl/?q=test#/myTab?filter={"q"%3A"test"}`

# Solution
Catch the natural form submit actions (with e.preventDefault)

Fix #9387

### CODE REVIEW

File: packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.tsx [hunk 1]
```diff
@@ -1,9 +1,9 @@
-import * as React from 'react';
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.tsx:1]: please revert the change in the order of imports

**Review by fzaninotto — CHANGES_REQUESTED** [review]
Could you please add a unit test?

File: packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.spec.tsx [hunk 2]
```diff
@@ -30,6 +30,14 @@ describe('FilterLiveSearch', () => {
         fireEvent.click(screen.getByLabelText('ra.action.clear_input_value'));
         expect(screen.queryAllByRole('listitem')).toHaveLength(27);
     });
+    it("input search shouldn't change url on submit", () => {
+        render(<Basic />);
+        const input = screen.getByRole('textbox', { name: 'ra.action.search' });
+        fireEvent.change(input, { target: { value: '23' } });
+        fireEvent.click(input);
+        fireEvent.submit(input);
+        expect(window.location.href).toBe('http://localhost/');
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.spec.tsx:39]: This test passes even without the change in the FilterLiveSearch component...

https://canro91.github.io/2021/02/05/FailingTest/

File: packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.spec.tsx [hunk 3]
```diff
@@ -30,6 +30,16 @@ describe('FilterLiveSearch', () => {
         fireEvent.click(screen.getByLabelText('ra.action.clear_input_value'));
         expect(screen.queryAllByRole('listitem')).toHaveLength(27);
     });
+    it("input search shouldn't change url on submit", () => {
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/list/filter/FilterLiveSearch.spec.tsx:33]: Still not good: this test passes even if I comment the preventDefault in `FilterLiveSearch`

**Review by fzaninotto — CHANGES_REQUESTED** [review]

**Review by fzaninotto — APPROVED** [review]
