### PR TITLE
Fix FormWithRedirect Props

### LINKED ISSUE #6081: Typo: `chilren` instead of `children`
I suppose this is really a typo. Even if it's intended, it's really confusing.

https://github.com/marmelab/react-admin/blob/4c62d18f2cbde22349f66ef9d857c36414201d1f/packages/ra-core/src/form/FormWithRedirect.tsx#L193

### PR DESCRIPTION
**Pull request by djhi**
Supersedes #6082
Fixes #6081

### CODE REVIEW

File: packages/ra-ui-materialui/src/form/SimpleFormView.tsx [hunk 1]
```diff
@@ -1,13 +1,13 @@
 import * as React from 'react';
-import { Children, FC, ReactElement } from 'react';
+import { Children, FC, ReactElement, ReactNode } from 'react';
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/form/SimpleFormView.tsx:2]: Linter warning

**Review by fzaninotto — CHANGES_REQUESTED** [review]

**Review by fzaninotto — APPROVED** [review]
