### PR TITLE
Fix `<MenuItemLink>` type by omitting `placeholder` prop

### LINKED ISSUE #9507: [v4 typescript] `<MenuItemLink>` seems now have missing placeholder prop
**What you were expecting:**
I expect when I follow the tutorial there would be no type error https://marmelab.com/react-admin/Buttons.html#menuitemlink

**What happened instead:**
There is a type related error

```
Property 'placeholder' is missing in type '{ to: string; primaryText: string; }' but required in type 'Pick<MenuItemLinkProps, "replace" | "slot" | "style" | "title" | "children" | "role" | "action" | "about" | "security" | "primaryText" | "id" | "type" | "key" | ... 275 more ... | "tooltipProps">'.(2741)
```

**Steps to reproduce:**
Go to the example below
Run $ yarn type-check and look for errors in the src/Layout.tsx file

**Related code:**
https://stackblitz.com/edit/github-cubnvw?file=src%2FLayout.tsx

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 4.16.2
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Safari
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by smeng9**
With this merge request https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67170 introduced into @types/react 18.2.43, `placeholder` prop is no longer in `HTMLAttributes`.

Somehow since 18.2.43 the `<MenuItemLink>` requires us to pass the `placeholder` prop to the `<a>` tag below, where there are no such prop defined in [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)

Closes #9507

### CODE REVIEW

File: packages/ra-ui-materialui/src/layout/MenuItemLink.tsx [hunk 1]
```diff
@@ -140,16 +140,19 @@ export const MenuItemLink = forwardRef<any, MenuItemLinkProps>((props, ref) => {
...
-    MenuItemProps<'li'> & {
-        leftIcon?: ReactElement;
-        primaryText?: ReactNode;
-        /**
-         * @deprecated
-         */
-        sidebarIsOpen?: boolean;
-        tooltipProps?: TooltipProps;
-    };
+export type MenuItemLinkProps = Omit<
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/layout/MenuItemLink.tsx:143]: I think you should put the Omit on the MenuItemProps, not the larger union.

**Review by fzaninotto — CHANGES_REQUESTED** [review]

**Review by fzaninotto — APPROVED** [review]

**Review by djhi — APPROVED** [review]

**Comment by djhi** [comment]
Thanks!
