### PR TITLE
Fix logout button appears in two different menus

### LINKED ISSUE #6228: the Mobile menu doesn't need the logout button
## Problem

On Mobile, the Logout button appears twice: once in the main menu, and once in the user menu.

logout

It's confusing, and has no UX justification. 

The reason is that it was added to the navigation menu before react-admin had a user menu. But when we added it to the user menu, we didn't remove it form the navigation menu.

## Solution

Don't render the logout menu item in the navigation menu.

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #6228

### CODE REVIEW

File: packages/ra-ui-materialui/src/layout/Menu.tsx [hunk 1]
```diff
@@ -89,12 +80,9 @@ const Menu: FC<MenuProps> = props => {
                         leftIcon={
                             resource.icon ? <resource.icon /> : <DefaultIcon />
                         }
-                        onClick={onMenuClick}
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/layout/Menu.tsx:92]: I refactored the `<MenuItemLink>` to let it pull the props it needs (rather than expecting them to be pushed by the `<Sidebar>`). 

This greatly simplifies the creation of custom menus.

File: docs/Theming.md [hunk 2]
```diff
@@ -843,71 +888,88 @@ const Menu = ({ onMenuClick, logout }) => {
...
-export default MyLayout;
+<MenuItemLink to="/custom-route" primaryText={
+    <Badge badgeContent={4} color="primary">
+        Notifications
+    </Badge>
+} />
 ```
 
-Then, use this layout in the `<Admin>` `layout` prop:
+The `icon` prop allows to set the menu left icon.
```
Comment (WiXSL) [inline docs/Theming.md:919]: `icon` => `leftIcon`

**Comment by fzaninotto** [comment]
Wait, since #5575 it's the menu's responsibility to reduce width when the sidebar is closed. I'm not sure why, but if it's the case this should be documented.

**Comment by fzaninotto** [comment]
OK, it's both the Sidebar AND the Menu's responsibility to reduce width, in order to support one use case: using a react-admin oss `<Menu>` inside a react-admin ee app. So we need to keep that in the ra oss code, but people who customize the menu in a re oss app don't need to implement open/closed state handling as it's already handled by the Sidebar. 

So this PR is ready.

File: docs/Theming.md [hunk 3]
```diff
@@ -807,9 +807,56 @@ Check [the `ra-preferences` documentation](https://marmelab.com/ra-enterprise/mo
...
+import { Layout }  from './Layout';
+
+const App = () => (
+    <Admin layout={Layout} dataProvider={simpleRestProvider('http://path.to.my.api')}>
+        // ...
+    </Admin>
+);
+```
+
+**Tip**: You can generate the menu items for each of the resourc emages by reading the Resource configurations from the Redux store:
```
Comment (djhi) [inline docs/Theming.md:859]: Something weird here

File: examples/demo/src/layout/Menu.tsx [hunk 4]
```diff
@@ -1,9 +1,8 @@
 import * as React from 'react';
 import { FC, useState } from 'react';
 import { useSelector } from 'react-redux';
-import SettingsIcon from '@material-ui/icons/Settings';
 import LabelIcon from '@material-ui/icons/Label';
-import { useMediaQuery, Theme, Box } from '@material-ui/core';
+import { Box } from '@material-ui/core';
```
Comment (djhi) [inline examples/demo/src/layout/Menu.tsx:5]: I thought we should avoid `Box`

File: examples/demo/src/layout/Menu.tsx [hunk 5]
```diff
@@ -22,17 +21,13 @@ import { AppState } from '../types';
 
 type MenuName = 'menuCatalog' | 'menuSales' | 'menuCustomers';
 
-const Menu: FC<MenuProps> = ({ onMenuClick, logout, dense = false }) => {
+const Menu: FC<MenuProps> = ({ dense = false }) => {
```
Comment (djhi) [inline examples/demo/src/layout/Menu.tsx:24]: Good opportunity to migrate away from `FC`

File: packages/ra-ui-materialui/src/layout/Menu.tsx (hunk 1 above)
Comment (djhi) [reply packages/ra-ui-materialui/src/layout/Menu.tsx:92]: Indeed :+1:

**Review by djhi — CHANGES_REQUESTED** [review]

**Review by djhi — APPROVED** [review]
