### PR TITLE
Notification component autoHideDuration prop not being used.

### LINKED ISSUE #4298: React Admin Notification third param as seconds has no effect.
**What you were expecting:**
The notification to stay as long as the number of seconds added in the third param
**What happened instead:**
The notification still uses the default timer and auto hides
**Steps to reproduce:**
I imported 
import { useNotify,useSafeSetState} from "react-admin";
const notify=useNotify();
notify("An email has been sent to you. Please check your SPAM for the email.",'info',500000);

**Related code:**
const notify=useNotify();
notify("An email has been sent to you. Please check your SPAM for the email.",'info',500000);

The code box on the post page has a test notification button 

https://codesandbox.io/s/great-hill-hm4zk

```
const notify=useNotify();
notify("An email has been sent to you. Please check your SPAM for the email.",'info',500000);

```

**Environment**
Dev
* React-admin version:3.1.2
* Last version that did not exhibit the issue (if applicable):
* React version:16.12.0
* Browser: Firefox/Chrome
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #4298

### CODE REVIEW

File: packages/ra-core/src/sideEffect/useNotify.ts [hunk 1]
```diff
@@ -27,12 +27,14 @@ const useNotify = () => {
             message: string,
             type: NotificationType = 'info',
             messageArgs: any = {},
-            undoable: boolean = false
+            undoable: boolean = false,
+            autoHideDuration: number
```
Comment (djhi) [inline packages/ra-core/src/sideEffect/useNotify.ts]: It should probably be optional:

```suggestion
            autoHideDuration?: number
```

**Comment by djhi** [comment]
I won't merge it now though because @fzaninotto may want to move it on `next`

**Comment by fzaninotto** [comment]
Thanks!
