### PR TITLE
Fix AutocompleteInput suggestions flicker when used inside ReferenceInput

### LINKED ISSUE #7767: ReferenceInput with AutocompleteInput flickers on search
**What you were expecting:**

When using AutocompleteInput with a ReferenceInput, the options list should not flicker

**What happened instead:**

Options list somehow appears to be filtered on client-side (matches entries containing the search term), which causes flickering when API returns a no-match.

**Steps to reproduce:**

1. Open code sandbox
2. In the preview window, go to Comments list
3. Click on the icon to create a new comment
4. Now click into the first input that says "Post"
5. Enter character "y"

**Related code:**

CodeSandbox: https://codesandbox.io/s/serene-sutherland-46rs3t?file=/src/comments/CommentCreate.tsx

**Other information:**

4f116c1676cacbc1b981211b5926ef17

**Environment**

* React-admin version: 4.1.1

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #7767

### CODE REVIEW

File: packages/ra-core/src/controller/input/useReferenceInputController.ts [hunk 1]
```diff
@@ -97,6 +97,7 @@ export const useReferenceInputController = <RecordType extends RaRecord = any>(
         },
         {
             enabled: isGetMatchingEnabled,
+            keepPreviousData: true,
```
Comment (fzaninotto) [inline packages/ra-core/src/controller/input/useReferenceInputController.ts:100]: This was the main cause of the flicker

File: packages/ra-ui-materialui/src/input/AutocompleteInput.tsx [hunk 2]
```diff
@@ -244,7 +246,7 @@ If you provided a React element for the optionText prop, you must also provide t
     }, [shouldRenderSuggestions, noOptionsText]);
 
     const getRecordRepresentation = useGetRecordRepresentation(resource);
-    const { getChoiceText, getChoiceValue, getSuggestions } = useSuggestions({
+    const { getChoiceText, getChoiceValue } = useSuggestions({
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.tsx:249]: we don't need to filter suggestions in AutocompleteInput, because:

- when used in standalone, AutocompleteInput already knows how to filter options
- when used inside a ReferenceInput, it's the responsibility of ReferenceInput to filter

Therefore, `getSuggestions` is useless.

File: packages/ra-ui-materialui/src/input/AutocompleteInput.tsx [hunk 3]
```diff
@@ -421,30 +429,6 @@ If you provided a React element for the optionText prop, you must also provide t
 
     const oneSecondHasPassed = useTimeout(1000, filterValue);
 
-    // To avoid displaying an empty list of choices while a search is in progress,
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.tsx:424]: Not necessary now that we have the keepPreviousData in the ReferenceInput

File: packages/ra-ui-materialui/src/input/AutocompleteInput.tsx [hunk 4]
```diff
@@ -421,30 +429,6 @@ If you provided a React element for the optionText prop, you must also provide t
...
-    // a second has passed.
-    const currentChoices = useRef(allChoices);
-
-    useEffect(() => {
-        if (allChoices && (allChoices.length > 0 || oneSecondHasPassed)) {
-            currentChoices.current = allChoices;
-        }
-    }, [allChoices, oneSecondHasPassed]);
-
-    const suggestions = useMemo(() => {
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.tsx:435]: We don't need to filter the suggestions ourselves: MUI's Autocomplete takes them all, but displays only the ones returned by `filterOptions`

File: packages/ra-ui-materialui/src/input/AutocompleteInput.tsx (hunk 2 above)
Comment (fzaninotto) [reply packages/ra-ui-materialui/src/input/AutocompleteInput.tsx:249]: Wait, I may have been a bit hasty on this one... I'll investigate a bit more.

**Review by septentrion-730n — APPROVED** [review]

**Review by arimet — APPROVED** [review]

**Comment by davidhenley** [comment]
We are getting the "The value provided to Autocomplete is invalid." warning again with this.

**Comment by fzaninotto** [comment]
@davidhenley II've just tested the simple example in the `next` branch and got no warning. Can you explain how you got this warning?

**Comment by davidhenley** [comment]
I got it when the selected value isn't in the getList call from the data provider that the autocomplete does on load. 

So say you have ids 1-25 on your getList call and the selected is is 26 on edit. 

When you choose id 1 or 2 or 3 or whatever you get this error on every autocomplete input. 

What's weird is the warning is about the old value and not the new value.

**Comment by fzaninotto** [comment]
> This was working fine in 4.2.5 and as soon as we updated I get this on every single AutocompleteInput

How could you update? This change hasn't been released as it's scheduled for react-admin 4.3, due end of this month.

**Comment by davidhenley** [comment]
Sorry, it wasn't this particular change then, another change in 4.2.6. Thanks.

**Comment by fzaninotto** [comment]
Then please open a new issue, and include a reproduction case based on the simple example codesandbox.

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
