### PR TITLE
[RFR] Fix SelectInput variant="standard" shows warning for unknown class

### LINKED ISSUE #3987: [v3] Error message: Material-UI: the key `adornedEnd` provided to the classes prop is not implemented in ForwardRef(Input). You can only override one of the following: root,formControl,focused,disabled,colorSecondary,underline,error,multiline,fullWidth,input,inputMarginDense,inputMultiline,inputTypeSearch.
**What happened instead:**

I use a SelectInput in a SimpleForm mentioned in document (https://marmelab.com/react-admin/doc/3.0-beta/Inputs.html#selectinput).
It can work, but it will show the error message.

**Related code:**

Here is how I use a SelectInput in a SimpleForm

```
const choices = [
    { _id: 123, full_name: 'Leo Tolstoi', sex: 'M' },
    { _id: 456, full_name: 'Jane Austen', sex: 'F' },
];

export default (props) => (
    <Edit {...props}>
            <SimpleForm
                variant="standard"
                submitOnEnter={false}
                redirect={false}
            >
                <TextInput source="plan_name" resettable />
                <SelectInput source="author_id" choices={choices} optionText="full_name" optionValue="_id" />
            </SimpleForm>
    </Edit>
)
```
**Environment**

* React-admin version: 3.0.0-beta.6
* React version: 16.11.0
* Browser: Chrome
* Stack trace (in case of a JS error):

Material-UI: the key `adornedEnd` provided to the classes prop is not implemented in ForwardRef(Input).
You can only override one of the following: root,formControl,focused,disabled,colorSecondary,underline,error,multiline,fullWidth,input,inputMarginDense,inputMultiline,inputTypeSearch. 
    in WithStyles(ForwardRef(Input)) (created by Select)
    in Select (created by WithStyles(ForwardRef(Select)))
    in WithStyles(ForwardRef(Select)) (created by TextField)
    in TextField (created by WithStyles(ForwardRef(TextField)))
    in WithStyles(ForwardRef(TextField)) (created by ResettableTextField)
    in ResettableTextField (created by SelectInput)
    in SelectInput (at PlanEdit.js:42)
    in Anonymous (created by WithPermissions)
    in WithPermissions (created by Router.Consumer)
    in Router.Consumer (created by Route)
    in Route (created by ResourceRoutes)
    in ResourceRoutes (created by Resource)
    in Resource (at App.js:27)
    in App (at src/​index.js:7)

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #3987

### CODE REVIEW

File: packages/ra-ui-materialui/src/input/ResettableTextField.js [hunk 1]
```diff
@@ -95,7 +95,10 @@ function ResettableTextField({
             classes={restClasses}
             value={value}
             InputProps={{
-                classes: { adornedEnd: props.select ? inputAdornedEnd : null },
+                classes:
+                    props.select && variant === 'filled'
```
Comment (djhi) [inline packages/ra-ui-materialui/src/input/ResettableTextField.js]: I don't get the fix. Why is it needed to check the variant ?

Comment (fzaninotto) [reply packages/ra-ui-materialui/src/input/ResettableTextField.js]: Because the `inputAdornedEnd` class doesn't exist in the standard variant of MUI's TextField. Unfortunately, the list of classes of all variants isn't the same, hence the warning that we have to fix.
