### PR TITLE
[RFR] Fix ArrayInput defaultValue

### LINKED ISSUE #2046: The default value of an ArrayInput doesn't work with a SimpleFormIterator
**What you were expecting:**
I want to have a default value for an `ArrayInput` with a `SimpleFormIterator` as a child.

**What happened instead:**
The input isn't populated as expected and stay empty.

**Steps to reproduce:**
1. Have an `ArrayInput` with a `SimpleFormIterator` as a child
2. Set the prop `defaultValue` with a correct format

**Related code:**

See the first input in `src/posts/PostCreate.js` file within the following Code Sandbox:
https://codesandbox.io/s/1wqxkv6pml

The code is the following:

```jsx
<ArrayInput
    source="backlinks"
    defautltValue={[
        { date: "2012-08-09T00:00:00.000Z", url: "http://example.com/bar/baz.html" }
    ]}
>
    <SimpleFormIterator>
        <DateInput source="date" />
        <TextInput source="url" />
    </SimpleFormIterator>
</ArrayInput>
```

**Other information:**
Related question on SO: https://stackoverflow.com/questions/51425225/arrayinput-how-to-set-default-value

**Environment**

* React-admin version: from **2.0.2** to **2.1.2** at least
* React version: 16.3.1
* Browser: Chrome

### PR DESCRIPTION
**Pull request by djhi**
Follow #2084 
Fixes #2046 

- [x] Introduce `withDefaultValue` to allow input components not using `addField` to dispatch the `initializeForm` action for their default values
- [x] Refactor FormField to use the new HOC
- [x] Use the new HOC in `ArrayInput`
- [x] Fix SimpleFormIterator so that it initializes correctly when it has default values
- [x] Tests

### CODE REVIEW

**Comment by fzaninotto** [comment]
The refactoring makes the change difficult to understand... Can you either split the commit into two (one refactoring, one fix), or explain what you've changed?

**Comment by djhi** [comment]
@fzaninotto Clearer ?

File: packages/ra-core/src/form/withDefaultValue.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+        }
+        initializeForm({
+            [source]:
+                typeof defaultValue === 'function'
+                    ? defaultValue()
+                    : defaultValue,
+        });
+    }
+
+    componentDidUpdate(prevProps) {
```
Comment (fzaninotto) [inline packages/ra-core/src/form/withDefaultValue.js]: why use `componentDidUpdate` instead of the previous `componentWillReceiveProps`?

File: packages/ra-core/src/form/withDefaultValue.js [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+        }
+    }
+
+    render() {
+        const { initializeForm, component, ...props } = this.props;
+        return createElement(component, props);
+    }
+}
+
+export default DecoratedComponent => {
```
Comment (fzaninotto) [inline packages/ra-core/src/form/withDefaultValue.js]: use shorthand function (loose the brackets and `return`)

File: packages/ra-core/src/form/withDefaultValue.spec.js [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+                    initializeForm={initializeForm}
+                    component={BaseComponent}
+                    source="bar"
+                    defaultValue="foo"
+                />
+            );
+            assert.equal(initializeForm.mock.calls.length, 1);
+            assert.deepEqual(initializeForm.mock.calls[0][0], { bar: 'foo' });
+
+            wrapper.setProps({ defaultValue: 'bar', initializeForm });
```
Comment (fzaninotto) [inline packages/ra-core/src/form/withDefaultValue.spec.js]: why do you reset `initializeForm`? It's a function...

File: packages/ra-ui-materialui/src/form/SimpleFormIterator.js [hunk 4]
```diff
@@ -65,7 +65,11 @@ export class SimpleFormIterator extends Component {
         // but redux-form doesn't provide one (cf https://github.com/erikras/redux-form/issues/2735)
         // so we keep an internal map between the field position and an autoincrement id
         this.nextId = 0;
-        this.ids = props.fields ? props.fields.map(() => this.nextId++) : [];
+        this.ids = props.defaultValue
+            ? props.defaultValue.map(() => this.nextId++)
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/form/SimpleFormIterator.js]: this one I don't understand. Can you explain the rationale?

File: cypress/integration/create.js [hunk 5]
```diff
@@ -15,6 +15,17 @@ describe('Create Page', () => {
         );
     });
 
+    it('should put the ArrayInput default value', () => {
+        const currentDate = new Date();
+        const currentDateString = currentDate.toISOString().slice(0, 10);
+        cy.get(CreatePage.elements.input('backlinks[0].date')).should(el =>
+            expect(el).to.have.value(currentDateString)
```
Comment (fzaninotto) [inline cypress/integration/create.js]: I'm afraid this is subject to race conditions, where the `Date` generated in the test and the one generated in the default value won't match.

File: packages/ra-core/src/form/withDefaultValue.js (hunk 1 above)
Comment (djhi) [reply packages/ra-core/src/form/withDefaultValue.js]: because `componentWillReceiveProps` is deprecated. See https://reactjs.org/blog/2018/03/29/react-v-16-3.html

File: cypress/integration/create.js (hunk 5 above)
Comment (djhi) [reply cypress/integration/create.js]: No more than in the first create test at L10

File: packages/ra-ui-materialui/src/form/SimpleFormIterator.js (hunk 4 above)
Comment (djhi) [reply packages/ra-ui-materialui/src/form/SimpleFormIterator.js]: Explained in comments

File: packages/ra-ui-materialui/src/form/SimpleFormIterator.js [hunk 6]
```diff
@@ -64,7 +64,16 @@ export class SimpleFormIterator extends Component {
         // but redux-form doesn't provide one (cf https://github.com/erikras/redux-form/issues/2735)
         // so we keep an internal map between the field position and an autoincrement id
         this.nextId = 0;
-        this.ids = props.fields ? props.fields.map(() => this.nextId++) : [];
+
+        // We check whether we have a defaultValue (which must be an array) before checking
+        // the fields prop which will always be empty for a new record.
+        // Without it, our ids wouldn't match the default value and we would get key warnings
+        // on the CssTransition element inside our render method
+        this.ids = props.defaultValue
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/form/SimpleFormIterator.js]: I still don't understand why you don't check `props.fields` *before* checking `props.defaultValue`. Here is my rationale:

1. if there is a record, use the fields
2. if there is no record, use the default value

The 1st case doesn't work like that with your code.

By the way, since `this.nextId` is initialized just above, I think a faster way to do `props.fields.map(() => this.nextId++)` is `this.nextId = props.fields.length`.
