### PR TITLE
[RFR] Fix AutocompleteInput

### LINKED ISSUE #4040: Default width for AutocompleteInput is different from the rest of the inputs
[The problem is described here.](https://github.com/marmelab/react-admin/issues/4011)

### PR DESCRIPTION
**Pull request by djhi**
Fixes #4040

Many classes weren't used at all so I removed them.

Besides, while testing this on the simple example, I noticed that `SimpleFormIterator` was adding a `div` because of the `TransitionGroup`. This `div` was inserted as the child of `ul` which breaks semantics and accessibility

image

### CODE REVIEW

File: packages/ra-ui-materialui/src/input/AutocompleteInput.tsx [hunk 1]
```diff
@@ -328,13 +332,6 @@ const AutocompleteInput: FunctionComponent<
                             name={input.name}
                             InputProps={{
                                 inputRef: storeInputRef,
-                                classes: {
-                                    root: classNames(classes.inputRoot, {
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.tsx]: this was used to support both filled and standard variants. I'm afraid this change breaks that. Can you make sure the form displays correctly with `<SimpleForm variant="standard">`?

Comment (djhi) [reply packages/ra-ui-materialui/src/input/AutocompleteInput.tsx]: Confirmed. It works by setting the variant on `SimpleForm`
