### PR TITLE
Fix SimpleFormIterator Labels

### LINKED ISSUE #7631: ArrayInput>SimpleFormIterator labels not working
**What you were expecting:**

Labels on inputs.

**What happened instead:**

No labels on inputs.

**Steps to reproduce:**

ArrayInput with Inputs nested: no labels.

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple?file=/src/posts/PostCreate.tsx

**Related code:**

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple?file=/src/posts/PostCreate.tsx

**Other information:**

This time I don't have to create a reproducible example because it's part of the example itself already.

It's the ArrayInput>SimpleFormIterator for Backlinks (the sandbox links should go to the correct file)

image

**Environment**

* React-admin version: master
* React version: whatever is on master

### PR DESCRIPTION
**Pull request by djhi**
Fixes #7631

### CODE REVIEW

File: packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorItem.tsx [hunk 1]
```diff
@@ -11,7 +11,8 @@ import {
 } from 'react';
 import { Typography } from '@mui/material';
 import clsx from 'clsx';
-import { RaRecord } from 'ra-core';
+import { getFieldLabelTranslationArgs, RaRecord, useTranslate } from 'ra-core';
+import inflection from 'inflection';
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIteratorItem.tsx:15]: Linter warning

**Review by fzaninotto — CHANGES_REQUESTED** [review]

**Review by slax57 — APPROVED** [review]

**Comment by slax57** [comment]
This fixes https://github.com/marmelab/react-admin/issues/7631 rather, doesn't it?

**Review by fzaninotto — APPROVED** [review]
