### PR TITLE
[4.0.0alpha.2] Demos fix useRecordContext usage

### LINKED ISSUE #7145: [4.0.0-alpha.2] Demos upgrade issues
Some CRM app components lack upgrade on accessing a record from `useRecordContext` instead of the `record` prop

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #7145

### CODE REVIEW

File: examples/crm/src/companies/CompanyCard.tsx [hunk 1]
```diff
@@ -59,9 +59,12 @@ const StyledMuiLink = styled(MuiLink)(({ theme }) => ({
     },
 }));
 
-export const CompanyCard = ({ record }: { record: Company }) => {
+export const CompanyCard = (props: { record: Company }) => {
     const [elevation, setElevation] = useState(1);
     const createPath = useCreatePath();
+    const record = useRecordContext<Company>(props);
```
Comment (djhi) [inline examples/crm/src/companies/CompanyCard.tsx:65]: I think we should you should put a RecordContextProvider in `GridList` if we really want to use the record context. Seems overkill to me as we manually pass the record

File: examples/crm/src/contacts/TagsList.tsx [hunk 2]
```diff
@@ -36,8 +36,10 @@ const ColoredChipField = (props: any) => {
     );
 };
 
-export const TagsList = ({ record }: { record: Contact }) => {
+export const TagsList = (props: { record: Contact }) => {
```
Comment (djhi) [inline examples/crm/src/contacts/TagsList.tsx:39]: Same remark for this one

**Review by djhi — APPROVED** [review]
