### PR TITLE
Fix logging of queries in ra-data-fakerest

### LINKED ISSUE #9959: ra-data-fakerest doesn't log response to the console
**What you were expecting:**
When opening the log line of a fakerest query, see the response

**What happened instead:**
it shows an empty Promise instead

image

**Steps to reproduce:**

1. Open the [simple example stackblitz](https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple)
2. Open the console
3. Develop one of the lines logged by the data provider

**Environment**

* React-admin version: 5.0.1
* Last version that did not exhibit the issue (if applicable): 4.x
* React version: 18
* Browser: Chrome

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #9959

### CODE REVIEW

File: packages/ra-data-fakerest/src/index.ts [hunk 1]
```diff
@@ -153,27 +153,27 @@ export default (data, loggingEnabled = false, delay?: number): DataProvider => {
...
                 `Undefined collection "${resource}"`
             );
             error.code = 1; // make that error detectable
-            return Promise.reject(error);
+            throw error;
         }
         let response;
         try {
-            response = getResponse(type, resource, params);
+            response = await getResponse(type, resource, params);
```
Comment (fzaninotto) [inline packages/ra-data-fakerest/src/index.ts:167]: This was the root cause: since the introduction of the delay in #9908, `getResponse` may return a Promise.

**Review by djhi — APPROVED** [review]
