### PR TITLE
Fix parsed date/date-time filter resets component

### LINKED ISSUE #7540: DateTimeInputs not working correctly as Filters
**What you were expecting:**
DateTimeInput components to work correctly as list filter components

**What happened instead:**
Month and date/time values do not register properly when values change, and often reset entirely while picker is active.

**Steps to reproduce:**
Add a DateTimeInput as a Filter component, then try to use the date picker to select a value.

**Related code:**
https://codesandbox.io/s/cool-sound-pdlsh4 Check the published_at filter on the Posts list view.

**Environment**

* React-admin version: 4.0.0.
* Last version that did not exhibit the issue (if applicable): 3.19.10
* React version: 17.0.2
* Browser: Chrome
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #7540

The problem is in the `getFilterFormValues` return value, if a field is a Date, and has a `parse` function that returns a date (this is why it happens by default in DateTimeInputs and not in DateInputs), its value gets treated like a regular object, and ends up returning an empty object for that field, instead of the string representation of the date

### CODE REVIEW

File: packages/ra-ui-materialui/src/list/filter/FilterForm.tsx [hunk 1]
```diff
@@ -237,9 +237,15 @@ const getInputValue = (
     key: string,
     filterValues: Record<string, any>
 ) => {
+    if (formValues[key] === undefined || formValues[key] === null) {
```
Comment (WiXSL) [inline packages/ra-ui-materialui/src/list/filter/FilterForm.tsx:240]: You get `null` when a DateInput/DateTimeInput  clear button is click by the user

**Review by fzaninotto — APPROVED** [review]
