### PR TITLE
Fix `DatagridConfigurable` column ordering feature does not work in Firefox

### LINKED ISSUE #8672: DataGridConfigurable column ordering feature does not work in Firefox
**What you were expecting:**

Column ordering (drag and drop the columns to reoreder them) works as illustrated in the [`DataGridConfigurable` docs](https://marmelab.com/react-admin/Datagrid.html#configurable)

**What happened instead:**

- In Chrome, the feature works as intended
- In Firefox, column ordering does not work

**Steps to reproduce:**

- Run the `OrderList` example in Firefox.
- Click on `Column` button
- Drag and drop the columns to reorder them (it doesn't work)

**Related code:**

I also tried one example ( https://wikidata-table.vercel.app/#/international-airports) provided in #8488 and it also doesn't work

**Other information:**

- Chrome:

[chrome.webm](https://user-images.githubusercontent.com/26686688/220283843-87292b05-377b-4541-a618-a5938da20e71.webm)

- Firefox:

[firefox.webm](https://user-images.githubusercontent.com/26686688/220283877-34febe24-8e6e-4b27-a9e3-5460bc36b5f9.webm)

**Environment**

* React-admin version: 4.8.1
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Chrome 110.0.5481.100, Firefox 110.0
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by slax57**
Fix #8672

## Related readings
- [Issue description in stackoverflow](https://stackoverflow.com/questions/11656061/why-is-event-clientx-incorrectly-showing-as-0-in-firefox-for-dragend-event)
- [Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=505521#c80)
- [Implemented solution](https://stackoverflow.com/a/24137885/3975522)

### CODE REVIEW

File: packages/ra-ui-materialui/src/preferences/FieldToggle.tsx [hunk 1]
```diff
@@ -11,18 +11,27 @@ export const FieldToggle = props => {
...
     const dropIndex = React.useRef<number>(null);
+    const x = React.useRef<number>(null);
+    const y = React.useRef<number>(null);
+
+    const handleDocumentDragOver = React.useCallback(event => {
+        x.current = event.clientX;
+        y.current = event.clientY;
+    }, []);
+
+    const handleDragStart = () => {
```
Comment (djhi) [inline packages/ra-ui-materialui/src/preferences/FieldToggle.tsx:22]: Probably missing a useCallback here

Comment (slax57) [reply packages/ra-ui-materialui/src/preferences/FieldToggle.tsx:22]: how come?

Comment (djhi) [reply packages/ra-ui-materialui/src/preferences/FieldToggle.tsx:22]: nvm

**Review by djhi — APPROVED** [review]
