### PR TITLE
Fix EmailField font size differs from other fields

### LINKED ISSUE #6566: EmailField showing larger text than all other Fields
EmailField is showing text at 16px when all other fields are 14px. Was this intentional?

It seems like the field is missing `MuiTypography-root MuiTypography-body2` on the `span` tag and the other have this.

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #6566

### CODE REVIEW

File: packages/ra-ui-materialui/src/field/EmailField.tsx [hunk 1]
```diff
@@ -34,9 +34,15 @@ const EmailField = memo<EmailFieldProps>((props: EmailFieldProps) => {
...
         >
-            {value}
+            <Typography
+                component="span"
+                variant="body2"
+                className={className}
+                {...sanitizeFieldRestProps(rest)}
+            >
+                {value}
+            </Typography>
```
Comment (djhi) [inline packages/ra-ui-materialui/src/field/EmailField.tsx:45]: I think you can pass these props directly to the `Link` component. See the example above this link: https://material-ui.com/components/links/#api

**Review by djhi — CHANGES_REQUESTED** [review]

File: packages/ra-ui-materialui/src/field/EmailField.tsx (hunk 1 above)
Comment (fzaninotto) [reply packages/ra-ui-materialui/src/field/EmailField.tsx:45]: Why should I? The props have to end up in the Typography element anyway.

Comment (fzaninotto) [reply packages/ra-ui-materialui/src/field/EmailField.tsx:45]: nevermind, you're right, I'll change that.

**Review by djhi — APPROVED** [review]
