### PR TITLE
[RFR] Fix DeleteWithConfirm throws exception

### LINKED ISSUE #3873: Cannot read property 'stopPropagation' of undefined when confirming record deletion
I am using react admin 3.0.0-beta.3 with dataProvider =  jsonServerProvider('http://jsonplaceholder.typicode.com'); 3.0.0-beta.3

I have a sample edit form for posts per react-admin tutorial (https://github.com/marmelab/react-admin/blob/next/docs/Tutorial.md) and added "undoable={false}" to edit form. This setting triggers confirmation prompt. When I click "confirm", I get an error "Cannot read property 'stopPropagation' of undefined". I also notice that the browser is javascript files. 

Attached screenprint shows files reloaded after I clicked confirm and the error message.
image

Source Code is attached.

[react-admin-app-3x.zip](https://github.com/marmelab/react-admin/files/3768781/react-admin-app-3x.zip)

### PR DESCRIPTION
**Pull request by fzaninotto**
closes #3873

### CODE REVIEW

File: packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.js [hunk 1]
```diff
@@ -98,16 +98,12 @@ const DeleteWithConfirmButton = ({
         e.stopPropagation();
     };
 
-    const handleDelete = useCallback(
-        event => {
-            event.stopPropagation();
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.js]: The event propagation is already stopped in `Confirm`
