### PR TITLE
[RFR] Fix ReferenceInput Ignore its sort prop

### LINKED ISSUE #3642: alpha.4 ReferenceInputController ignores sort parameter
**What you were expecting:**
Setting the sort parameter in a ReferenceInput element should set the sort options forwarded to the server.

**What happened instead:**
The sort options are ignored.

**Steps to reproduce:**
Create a ReferenceInput with a sort parameter a look at the request sent to the server.

**Related code:**
```
      <ReferenceInput
        label="Away Team"
        source="thumbnailMetadata.awayTeamId"
        reference={ApiResources.teamInformation.name}
        sort={{ field: 'name', order: 'ASC' }}
        perPage={100}
      >
        <SelectInput optionText="name" />
      </ReferenceInput
```
l
**Other information:**
The problem occurs in `packages/ra-core/src/controller/input/useReferenceInputController.ts`. See line 79:

```
const useReferenceInputController = ({
    input,
    perPage = 25,
    filter = defaultFilter,
    reference,
    filterToQuery,
    referenceSource = defaultReferenceSource,
    resource,
    source,
    // sort, <-- should be here
}: Option): ReferenceInputValue => {
    const translate = useTranslate();

    const { pagination, setPagination } = usePaginationState({ perPage });
    const { sort, setSort } = useSortState(/* should set default sort state here */);
    
```

The sort option is ignored. I can set the sort order from the child element but I can't set the sort from the ReferenceInput.

**Environment**

* React-admin version: 3.0.0-alpha.4
* Last version that did not exhibit the issue (if applicable): Pre 3.0
* React version: N/A
* Browser: N/A
* Stack trace (in case of a JS error): N/A

### PR DESCRIPTION
**Pull request by djhi**
Fixes #3642

### CODE REVIEW

File: packages/ra-core/src/controller/input/useReferenceInputController.ts [hunk 1]
```diff
@@ -84,12 +87,23 @@ const useReferenceInputController = ({
...
     const translate = useTranslate();
 
     const { pagination, setPagination } = usePaginationState({ perPage });
-    const { sort, setSort } = useSortState();
+    const { sort, setSort } = useSortState(sortOverride);
+
+    // We need to keep the current sort synchronized with the sort prop
+    // because the inner component may call the setSort too
+    useEffect(() => {
+        if (!isEqual(sort, sortOverride)) {
```
Comment (fzaninotto) [inline packages/ra-core/src/controller/input/useReferenceInputController.ts]: why the `!`? I'd expect that the effect does nothing if the props are equal, and sets the sort if the props are different. That makes me think that you are probably missing a unit test.
