### PR TITLE
[RFR] Fix hide filter button isn't aligned with field

### LINKED ISSUE #3432: "hide filter" button is not aligned
Screenshot from 2019-07-21 14-49-36

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #3432

Before:

image

After:

image

### CODE REVIEW

File: packages/ra-ui-materialui/src/list/FilterFormInput.js [hunk 1]
```diff
@@ -3,23 +3,38 @@ import PropTypes from 'prop-types';
...
 import { useTranslate } from 'ra-core';
 
 const emptyRecord = {};
 
 const sanitizeRestProps = ({ alwaysOn, ...props }) => props;
 
-const FilterFormInput = ({ filterElement, handleHide, classes, resource }) => {
+const useStyles = makeStyles(theme => ({
+    body: { display: 'flex', alignItems: 'flex-end' },
+    spacer: { width: '1em' },
```
Comment (djhi) [inline packages/ra-ui-materialui/src/list/FilterFormInput.js]: It would be better to use `theme.spacing` here too so that spaces are consistent
