### PR TITLE
Simplify useConfigureAdminRouterFromChildren permissions

### LINKED ISSUE #7637: Cannot log in to the e-commerce demo
on master, when I'm not logged in, entering anything in the login form has no effect. 

It seems I'm redirected to the dashboard and then immediately afterwards back to the login page. 

this doesn't happen in the simple example. 

latest version that did not show the bug: v4.0.2 - regression caused by #7609 or #7606 IMO

image

### PR DESCRIPTION
**Pull request by djhi**
Fixes #7637

### CODE REVIEW

File: packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx [hunk 1]
```diff
@@ -43,7 +43,7 @@ import { useResourceDefinitionContext } from './useResourceDefinitionContext';
 export const useConfigureAdminRouterFromChildren = (
     children: AdminChildren
 ): RoutesAndResources & { status: AdminRouterStatus } => {
-    const permissions = usePermissionsWithLogout();
```
Comment (djhi) [inline packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx:46]: `usePermissions` already handle the case when there is no authProvider

**Review by slax57 — APPROVED** [review]
works like a charm 🙂

**Review by fzaninotto — APPROVED** [review]
