### PR TITLE
Fix Demo glitches

### LINKED ISSUE #7281: [v4 beta] The "save" text is not translated but shown as a key: `ra.action.save`
**What you were expecting:**

The SAVE button to show the word `Save`

**What happened instead:**

The SAVE button shows the word `ra.action.save`

**Steps to reproduce:**

Just start a CREATE action for any resource and look at the "Save" button's text:

image

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

**Other information:**

**Environment**

React-admin version: "react-admin": "^4.0.0-beta.1"
Last version that did not exhibit the issue (if applicable):
React version: "react": "^17.0.2"
Browser:
Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #7281

### CODE REVIEW

File: examples/demo/src/products/ProductEdit.tsx [hunk 1]
```diff
@@ -150,7 +150,6 @@ const ProductEdit = () => (
                 <ReferenceManyField
                     reference="reviews"
                     target="product_id"
-                    label={false}
                     pagination={<Pagination />}
                     fullWidth
```
Comment (WiXSL) [inline examples/demo/src/products/ProductEdit.tsx:154]: NOTE: How to solve `fullWith` with `RefenceManyField` + children ?

**Review by djhi — APPROVED** [review]
