### PR TITLE
[RFR] Fix Autocomplete list is cut off by content area

### LINKED ISSUE #2097: Autocomplete list is cut off by content area
bug_autocomplete

**Environment**

* React-admin version: 2.1.4
* React version: 16.3.0
* Browser: Google Chrome 68.0.3440.75

### PR DESCRIPTION
**Pull request by djhi**
The fix introduced by #2123 has been reverted by #2159. This PR apply the fix again, correctly setting the z-index this time.

Fixes #2097

Before:
Before

After:
After

### CODE REVIEW

File: packages/ra-ui-materialui/src/input/AutocompleteInput.js [hunk 1]
```diff
@@ -304,12 +314,23 @@ export class AutocompleteInput extends React.Component {
...
         return (
-            <Paper {...containerProps} square>
-                {children}
-            </Paper>
+            <Popper
+                className={className}
+                open
+                anchorEl={this.inputEl}
+                placement="bottom-start"
+                popperOptions={{ positionFixed: true }}
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput.js]: please use a constant here to avoid [the infamous `{{` effect](https://marmelab.com/blog/2017/02/06/react-is-slow-react-is-fast.html#beware-of-object-literals-in-jsx).

Comment (djhi) [reply packages/ra-ui-materialui/src/input/AutocompleteInput.js]: Actually, this prop wasn't needed
