### PR TITLE
Fix `FilterButton` throws error if no filters are present 

### LINKED ISSUE #7026: Adding<FilterButton /> cause an error  "Uncaught TypeError: Cannot read properties of undefined (reading 'filter')"
**What you were expecting:**
Work as expected out of the box

**What happened instead:**
`Uncaught TypeError: Cannot read properties of undefined (reading 'filter')` when I added `<FilterButton />`

**Steps to reproduce:**
This almost clear boilerplate 

**Related code:**
App.tsx
```
const App = () => (
  <Admin
    loginPage={LoginPage}
    dataProvider={dataProvider}
    authProvider={authProvider}
  >
    <Resource
      name="v1/user"
      list={UserList}
      create={UserCreate}
      icon={UserIcon}
      edit={UserEdit}
      show={UserShow}
    />
  </Admin>
);
```
UserList.tsx
```
const ListActions = (props: any) => {
  return (
    <TopToolbar>
      <FilterButton />
      <CreateButton />
      <ExportButton />
    </TopToolbar>
  );
};

const UserList = (props: any) => {
  return (
    <List {...props} actions={<ListActions />}>
      <Datagrid>
        <TextField source="id" />
        <TextField source="name" />
        <EmailField source="email" />
      </Datagrid>
    </List>
  );
};
```

**Environment**

* React-admin version: "^3.19.5"
* Last version that did not exhibit the issue (if applicable): none
* React version: "^17.0.2"
* Browser: chrome
* Stack trace (in case of a JS error):
```
Uncaught TypeError: Cannot read properties of undefined (reading 'filter')
    at FilterButton (FilterButton.js:46)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at unbatchedUpdates (react-dom.development.js:22438)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:26020)
    at Object.render (react-dom.development.js:26103)
    at Module.<anonymous> (index.tsx:7)
    at Module../src/index.tsx (index.tsx:18)
    at __webpack_require__ (bootstrap:856)
    at fn (bootstrap:150)
    at Object.1 (reportWebVitals.ts:16)
    at __webpack_require__ (bootstrap:856)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
FilterButton @ FilterButton.js:46
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
unbatchedUpdates @ react-dom.development.js:22438
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ index.tsx:7
./src/index.tsx @ index.tsx:18
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
1 @ reportWebVitals.ts:16
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1 
        
       The above error occurred in the <FilterButton> component:

    at FilterButton (http://localhost:3000/static/js/vendors~main.chunk.js:158934:27)
    at div
    at Toolbar (http://localhost:3000/static/js/vendors~main.chunk.js:32152:23)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:42205:31)
    at TopToolbar (http://localhost:3000/static/js/vendors~main.chunk.js:155120:25)
    at ListActions (http://localhost:3000/static/js/main.chunk.js:912:5)
    at div
    at Toolbar (http://localhost:3000/static/js/vendors~main.chunk.js:32152:23)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:42205:31)
    at ListToolbar (http://localhost:3000/static/js/vendors~main.chunk.js:156225:31)
    at div
    at ListView (http://localhost:3000/static/js/vendors~main.chunk.js:156325:23)
    at ListContextProvider (http://localhost:3000/static/js/vendors~main.chunk.js:109670:18)
    at List (http://localhost:3000/static/js/vendors~main.chunk.js:155865:79)
    at UserList
    at WithPermissions (http://localhost:3000/static/js/vendors~main.chunk.js:108000:26)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:196162:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:196364:29)
    at ResourceContextProvider (http://localhost:3000/static/js/vendors~main.chunk.js:116984:21)
    at ResourceRoutes (http://localhost:3000/static/js/vendors~main.chunk.js:116850:20)
    at Resource (http://localhost:3000/static/js/vendors~main.chunk.js:116922:18)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:196162:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:196364:29)
    at RoutesWithLayout (http://localhost:3000/static/js/vendors~main.chunk.js:117111:24)
    at div
    at main
    at div
    at div
    at LayoutWithoutTheme (http://localhost:3000/static/js/vendors~main.chunk.js:153456:24)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:42205:31)
    at C (http://localhost:3000/static/js/vendors~main.chunk.js:196419:37)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:193211:75)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:40907:24)
    at Layout (http://localhost:3000/static/js/vendors~main.chunk.js:153574:26)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:196162:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:196364:29)
    at div
    at CoreAdminRouter (http://localhost:3000/static/js/vendors~main.chunk.js:116486:87)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:196162:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:196364:29)
    at CoreAdminUI (http://localhost:3000/static/js/vendors~main.chunk.js:116702:18)
    at AdminUI
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:195793:30)
    at ConnectedRouter (http://localhost:3000/static/js/vendors~main.chunk.js:49157:7)
    at ConnectedRouterWithContext (http://localhost:3000/static/js/vendors~main.chunk.js:49280:25)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:193211:75)
    at TranslationProvider (http://localhost:3000/static/js/vendors~main.chunk.js:125498:28)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:192922:20)
    at CoreAdminContext (http://localhost:3000/static/js/vendors~main.chunk.js:116249:28)
    at AdminContext
    at Admin (http://localhost:3000/static/js/vendors~main.chunk.js:160696:25)
    at App

React will try to recreate this component tree from scratch using the error boundary you provided, LayoutWithoutTheme.
```

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #7026

### CODE REVIEW

**Comment by fzaninotto** [comment]
As I explained in the linked issue, I don't think this is the right fix.

File: packages/ra-ui-materialui/src/list/filter/FilterButton.tsx [hunk 1]
```diff
@@ -73,6 +73,10 @@ const FilterButton = (props: FilterButtonProps): JSX.Element => {
         [showFilter, setOpen]
     );
 
+    if (!hiddenFilters) {
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/list/filter/FilterButton.tsx:76]: this will throw as soon as all the filters are shown. Not good!

**Review by fzaninotto — CHANGES_REQUESTED** [review]

File: packages/ra-ui-materialui/src/list/filter/FilterButton.tsx (hunk 1 above)
Comment (WiXSL) [reply packages/ra-ui-materialui/src/list/filter/FilterButton.tsx:76]: When all the filters are shown, `hiddenFilters` will be an empty array, `!hiddenFilters` will be false.
I can improve it by asking for `undefined`, but It should work as it is

Comment (fzaninotto) [reply packages/ra-ui-materialui/src/list/filter/FilterButton.tsx:76]: Yes, you're right. But see my (edited) comment: your code is correct but probably not the clearest way to do it.

Comment (WiXSL) [reply packages/ra-ui-materialui/src/list/filter/FilterButton.tsx]: You are right, I didn't ask if `filters` was defined, because I was under the wrong idea that I was returning, which I cannot do because of the hooks.

**Review by fzaninotto — APPROVED** [review]
