### PR TITLE
[RFR] Fix create to edit form values 

### LINKED ISSUE #2324: 2.3.0 - CreateForm with single TextInput doesn't show any value after form submission
**What you were expecting:**
CreateForm with single TextInput should show stored valued after form submssion

**What happened instead:**
CreateForm with single TextInput doesn't show any value after form submission

**Steps to reproduce:**
Post -> Create -> add title -> Save

**Related code:**
* https://codesandbox.io/s/6w0v218loz

* React-admin version: 2.3.0 / 2.3.1
* Last version that did not exhibit the issue (if applicable):

### PR DESCRIPTION
**Pull request by djhi**
- [x] Added an e2e test
- [x] Added a form middleware intercepting location changes
- [x] Unit test the middleware

Fixes #2324

### CODE REVIEW

File: packages/ra-core/src/form/formMiddleware.js [hunk 1]
```diff
@@ -0,0 +1,16 @@
+import { LOCATION_CHANGE } from 'react-router-redux';
+import { beforeLocationChange } from '../actions/formActions';
+
+const formMiddleware = () => next => action => {
```
Comment (fzaninotto) [inline packages/ra-core/src/form/formMiddleware.js]: I and other developers will be unable to understand why you're doing that. This file requires many, many comments to describe the issue and the solution.

**Comment by djhi** [comment]
Oh no, now that it is RFR and green, that's the moment where you say "Can you target next?", right @fzaninotto? :sob:

**Comment by djhi** [comment]
> I think you must update the CustomApp doc, too.

Actually the `CustomApp` doc was outdated and still referencing the `formMiddleware`
