### PR TITLE
[RFR] Fix double asterix on required RadioButtonGroupInput

### LINKED ISSUE #2395: RadioButtonGroupInput: required() validation adds two asterisks instead of one
Self explanatory title.

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #2395

Incidentally, this bug teaught me that material-ui now handles the required label at the `FormControl` level. We'll have to use that in the future.

### CODE REVIEW

File: packages/ra-ui-materialui/src/input/RadioButtonGroupInput.js [hunk 1]
```diff
@@ -132,17 +132,11 @@ export class RadioButtonGroupInput extends Component {
         return (
             <FormControl
                 component="fieldset"
-                required={isRequired}
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/RadioButtonGroupInput.js]: `FieldTitle` already handles that (see line 144)
