### PR TITLE
Fix improve SaveButton enable state

### LINKED ISSUE #8258: `ArrayInput` makes edited form always dirty on input blur
1- Goto to the simple example project: https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple?file=src%2Findex.tsx
2- Copy "authors" `ArrayInput` from `PostEdit` form and paste it inside `CommentEdit` form.
3- Edit any Comment record.
4- Focus any input and then blur it

Expected: 
`SaveButton` state is disabled

Result:
`SaveButton` state is enabled

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #8258

**PROBLEM**

`SaveButton` enable state may be true, even though no inputs have been changed.

This is because `useFormState().isDirty` might differ from `useFormState().dirtyFields` (https://github.com/react-hook-form/react-hook-form/issues/4740)
This is the expected behavior of `react-hook-form` and it may happen when you have a missing `defaultValue` for one of the inputs

· `dirtyFields` will mark the field dirty or not individually.
· `isDirty` will always do a deep equal against your defaultValues to determined form is dirty or not.
https://github.com/react-hook-form/react-hook-form/discussions/7860#discussioncomment-2208434

This is key, since `defaultValue` prop might be `undefined`, and in some cases you end up with `isDirty` being `true` but `dirtyFields` being an empty object. Like in the test I've added in this PR, plus the ones I've fixed in this PR

**SOLUTION**

Use `useFormState().dirtyFields` to enable/disable `SaveButton` instead of `useFormState().isDirty`

### CODE REVIEW

File: packages/ra-ui-materialui/src/button/SaveButton.tsx [hunk 1]
```diff
@@ -65,7 +65,8 @@ export const SaveButton = <RecordType extends RaRecord = any>(
     const translate = useTranslate();
     const form = useFormContext();
     const saveContext = useSaveContext();
-    const { isDirty, isValidating, isSubmitting } = useFormState();
+    const { dirtyFields, isValidating, isSubmitting } = useFormState();
+    const isDirty = Object.keys(dirtyFields).length;
```
Comment (WiXSL) [inline packages/ra-ui-materialui/src/button/SaveButton.tsx:69]: `useFormState().isDirty` might differ from `useFormState().dirtyFields` (https://github.com/react-hook-form/react-hook-form/issues/4740)

File: packages/ra-ui-materialui/src/button/SaveButton.spec.tsx [hunk 2]
```diff
@@ -400,4 +405,58 @@ describe('<SaveButton />', () => {
...
+                                },
+                            },
+                        ],
+                    }}
+                >
+                    <TextInput source="test" />
+                    <ArrayInput resource="foo" source="arr">
+                        <SimpleFormIterator>
+                            <NumberInput source="id" />
+                            <ArrayInput resource="bar" source="arr.nested">
```
Comment (slax57) [inline packages/ra-ui-materialui/src/button/SaveButton.spec.tsx:439]: Something seems weird in your test: `arr.nested` is not an array

File: packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx [hunk 3]
```diff
@@ -223,7 +223,7 @@ describe('<DateTimeInput />', () => {
             const onSubmit = jest.fn();
             render(
                 <AdminContext dataProvider={testDataProvider()}>
-                    <SimpleForm onSubmit={onSubmit}>
+                    <SimpleForm mode="onBlur" onSubmit={onSubmit}>
```
Comment (slax57) [inline packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx:226]: Now this worries me a bit. Why did you need to change this test?

**Review by slax57 — CHANGES_REQUESTED** [review]

File: packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx (hunk 3 above)
Comment (WiXSL) [reply packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx:226]: Well, it seems that the save button wasn't being enabled, which, should be right, I think it was wrong before

File: packages/ra-ui-materialui/src/button/SaveButton.spec.tsx (hunk 2 above)
Comment (WiXSL) [reply packages/ra-ui-materialui/src/button/SaveButton.spec.tsx:443]: You are right

File: packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx (hunk 3 above)
Comment (slax57) [reply packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx:226]: It's really weird that the test passed before this PR then.

But you convinced me your fix is right. Let's keep it.

Comment (WiXSL) [reply packages/ra-ui-materialui/src/input/DateTimeInput.spec.tsx:226]: Actually, my explanation of why this test should be right wasn't precise, is not relevant that the input is required, but that is being cleared and back to not being dirty, which is what matters to the SaveButton disable state

File: packages/ra-ui-materialui/src/button/SaveButton.tsx (hunk 1 above)
Comment (fzaninotto) [reply packages/ra-ui-materialui/src/button/SaveButton.tsx:69]: Could you add that as a comment above this line? It'd help future us understand why we're not using `isDirty` here. 

also, I'm nipticking, but I'd prefer

```jsx
const isDirty = Object.keys(dirtyFields).length > 0;
```

File: packages/ra-ui-materialui/src/button/SaveButton.spec.tsx [hunk 4]
```diff
@@ -400,4 +405,62 @@ describe('<SaveButton />', () => {
...
+                                ],
+                            },
+                        ],
+                    }}
+                >
+                    <TextInput source="test" />
+                    <ArrayInput resource="foo" source="arr">
+                        <SimpleFormIterator>
+                            <NumberInput source="id" />
+                            <ArrayInput resource="bar" source="arr.nested">
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/button/SaveButton.spec.tsx:443]: Why do you need two tested arrayinputs to test that case?

**Review by fzaninotto — CHANGES_REQUESTED** [review]
Nice work!

File: packages/ra-ui-materialui/src/button/SaveButton.spec.tsx (hunk 4 above)
Comment (WiXSL) [reply packages/ra-ui-materialui/src/button/SaveButton.spec.tsx]: You're right! I can simplify it

**Review by fzaninotto — APPROVED** [review]
