### PR TITLE
[RFR] Allow the FormDataConsumer to be used inside an ArrayInput

### LINKED ISSUE #1938: FormDataConsumer passes undefined as source inside ArrayInput
**What you were expecting:**
`<FormDataConsumer>` passes the correct source path when inside an `<ArrayInput`> element.

**What happened instead:**
Instead of passing the source `attachments[0].title` it is passing `attachments[0].undefined`.

**Steps to reproduce:**
Put the `<FormDataConsumer>` example from [documentation](https://marmelab.com/react-admin/Inputs.html#linking-two-inputs) inside `<ArrayInput>` element.

**Related code:**
```
export const ArticleCreate = (props) => (
    <Create {...props}>
        <SimpleForm>
            <TextInput source="text"/>
            <FormDataConsumer>
                {({ formData, ...rest }) =>
                    <TextInput source="text" {...rest} />
                }
            </FormDataConsumer>
            <ArrayInput source="attachments">
                <SimpleFormIterator>
                    <TextInput source="title"/>
                    <FormDataConsumer>
                        {({ formData, ...rest }) =>
                            <TextInput source="title" {...rest} />
                        }
                    </FormDataConsumer>
                </SimpleFormIterator>
            </ArrayInput>
        </SimpleForm>
    </Create>
);
```

**Images:**

- https://image.ibb.co/jVjbxy/1.png
- https://image.ibb.co/b9GpHy/2.png

**Environment**

* React-admin version: 2.0.3
* React version: 16.4.0
* Browser: Chrome

### PR DESCRIPTION
**Pull request by djhi**
Fix #1938

### CODE REVIEW

File: cypress/integration/create.js [hunk 1]
```diff
@@ -33,11 +33,25 @@ describe('Create Page', () => {
...
         cy.get(CreatePage.elements.addAuthor).click();
         cy.get(CreatePage.elements.input('authors[0].user_id')).should(
             el => expect(el).to.exist
         );
+        cy.get(CreatePage.elements.input('authors[0].role')).should(
+            el => expect(el).to.not.exist
+        );
+    });
+
+    it.only('should have a working array input with a scoped FormDataConsumer', () => {
```
Comment (fzaninotto) [inline cypress/integration/create.js]: `.only` spotted

File: docs/Inputs.md [hunk 2]
```diff
@@ -1284,6 +1284,42 @@ const OrderEdit = (props) => (
...
+- `getSource`: a function which will translate the source into a valid one for the `ArrayInput`
+
+```jsx
+import { FormDataConsumer } from 'react-admin';
+
+const PostEdit = (props) => (
+    <Edit {...props}>
+        <SimpleForm>
+            <ArrayInput source="authors">
+                <TextInput source="name" />
```
Comment (fzaninotto) [inline docs/Inputs.md]: missing `SimpleFormIterator`

File: packages/ra-core/src/form/FormDataConsumer.js [hunk 3]
```diff
@@ -42,8 +43,58 @@ const REDUX_FORM_NAME = 'record-form';
...
  * );
  */
-const FormDataConsumer = ({ children, formData, ...rest }) => {
-    const ret = children({ formData, ...rest });
+const FormDataConsumer = ({ children, formData, source, ...rest }) => {
+    let scopedFormData = formData;
+    let getSource;
+    let getSourceHasBeenCalled = false;
+
+    // If we have a source, we are in an ArrayInput component
```
Comment (fzaninotto) [inline packages/ra-core/src/form/FormDataConsumer.js]: I'm not very confident about this assumption. It seems an indirect way of detecting that we are in an `ArrayInput` component, based on the current `SimpleFormIterator` implementation. Isn't there a more robust way to detect it?

File: packages/ra-core/src/form/FormDataConsumer.js [hunk 4]
```diff
@@ -42,8 +43,58 @@ const REDUX_FORM_NAME = 'record-form';
...
+    if (source) {
+        const matches = ARRAY_SOURCE_REGEX.exec(source);
+
+        if (matches.length > 2) {
+            const [, arraySource, index] = matches;
```
Comment (fzaninotto) [inline packages/ra-core/src/form/FormDataConsumer.js]: I'm surprised that it lints

File: packages/ra-core/src/form/FormDataConsumer.js [hunk 5]
```diff
@@ -42,8 +43,58 @@ const REDUX_FORM_NAME = 'record-form';
...
+            scopedFormData = formData[arraySource][parseInt(index)];
+            getSource = scopedSource => {
+                getSourceHasBeenCalled = true;
+                return `${arraySource}[${index}].${scopedSource}`;
```
Comment (fzaninotto) [inline packages/ra-core/src/form/FormDataConsumer.js]: you should use `lodash.get()`, because there may be a nested object, e.g. `<TextInput source="author.name" />`

File: packages/ra-core/src/form/FormDataConsumer.js [hunk 6]
```diff
@@ -3,6 +3,7 @@ import { connect } from 'react-redux';
 import { getFormValues } from 'redux-form';
 
 const REDUX_FORM_NAME = 'record-form';
+const ARRAY_SOURCE_REGEX = /^(.*)\[(\d*)\]/;
```
Comment (fzaninotto) [inline packages/ra-core/src/form/FormDataConsumer.js]: I think the actual shape differs a bit. When I look at `SimpleFormIterator`'s way of recreating the source, it reads like this:

```
${member}.${input.props.source}
```

Where `member` is something like `backlinks[3]`.

So when used with a `SimpleFormIterator`, which has no `source`, the result has a closing dot (``backlinks[3].`). This `source` doesn't make sense, and I don't think you should use it inside `SimpleFormIterator`. Instead, you should detect in `SimpleFormIterator` when the child has no `source`, and inject the `index` instead.

File: packages/ra-core/src/form/FormDataConsumer.js [hunk 7]
```diff
@@ -42,8 +43,58 @@ const REDUX_FORM_NAME = 'record-form';
...
+    if (
+        ret &&
+        !getSourceHasBeenCalled &&
+        process.env.NODE_ENV !== 'production'
+    ) {
+        console.warn( // eslint-disable-line
+            `You have an input inside a FormDataConsumer inside an ArrayInput and you did not called the getSource function supplied by the FormDataConsumer component. This is required for your input to get the proper source and name.
+
+            <ArrayInput source="users">
+                <TextInput source="name" />
```
Comment (fzaninotto) [inline packages/ra-core/src/form/FormDataConsumer.js]: Missing `SimpleFormIterator`

File: packages/ra-core/src/form/FormDataConsumer.js [hunk 8]
```diff
@@ -42,8 +43,58 @@ const REDUX_FORM_NAME = 'record-form';
...
+
+    if (
+        ret &&
+        !getSourceHasBeenCalled &&
+        process.env.NODE_ENV !== 'production'
+    ) {
+        console.warn( // eslint-disable-line
+            `You have an input inside a FormDataConsumer inside an ArrayInput and you did not called the getSource function supplied by the FormDataConsumer component. This is required for your input to get the proper source and name.
+
+            <ArrayInput source="users">
```
Comment (fzaninotto) [inline packages/ra-core/src/form/FormDataConsumer.js]: the auto formatting added *a lot* of leading spaces on each line, which I don't think will look good on the console.

Comment (djhi) [reply packages/ra-core/src/form/FormDataConsumer.js]: It was fine but I extracted it anyway to be sure :)

screen

I indented the code on purpose but it may be not so nice to copy/paste it with this indentation. What do you think?

File: packages/ra-core/src/form/FormDataConsumer.js (hunk 3 above)
Comment (djhi) [reply packages/ra-core/src/form/FormDataConsumer.js]: Like passing an optional prop?

File: packages/ra-core/src/form/FormDataConsumer.js (hunk 5 above)
Comment (djhi) [reply packages/ra-core/src/form/FormDataConsumer.js]: We're generating a string here, from another string.

File: packages/ra-core/src/form/FormDataConsumer.js (hunk 6 above)
Comment (djhi) [reply packages/ra-core/src/form/FormDataConsumer.js]: In the case of the `FormDataConsumer`, which has no `source`, we end up with `backlinks[3].undefined`

Comment (djhi) [reply packages/ra-core/src/form/FormDataConsumer.js]: Thanks to your inputs, I ended up not using any regex at all :+1:

File: packages/ra-core/src/form/FormDataConsumer.js (hunk 5 above)
Comment (paulito415) [reply packages/ra-core/src/form/FormDataConsumer.js]: Hi @djhi,

First, thanks for the awesome `FormDataConsumer` - really central and useful component for react-admin. I have a quick question but couldn't find you on the Discord at reactiflux. 

I have a nested `ArrayInput` both of which have `FormDataConsumer` within. In my inner `FormDataConsumer`, when I set `source={getSource('field')}` on the page it shows it's still getting the outer `getSource` element. Is there a way for me to really get the inside one?

Thanks,
Paul

Comment (djhi) [reply packages/ra-core/src/form/FormDataConsumer.js]: Please use StackOverflow as explained in the issue template

Comment (paulito415) [reply packages/ra-core/src/form/FormDataConsumer.js]: OK just did - https://stackoverflow.com/questions/60343419/how-to-call-getsource-within-nested-arrayinput-formdataconsumer-in-react-admin. Thanks!

Comment (paulito415) [reply packages/ra-core/src/form/FormDataConsumer.js]: Hi @djhi sorry to contact you here again. But other than stack overflow, is there any other place I can ask this question? Are the #help-js and #help-react channels on Discord at reactiflux an appropriate place? I just actually wanted to know whether this is supported. If not, I can quickly change my way of doing this, instead of continuing to bang my head on the wall :) Thanks!

Comment (fzaninotto) [reply packages/ra-core/src/form/FormDataConsumer.js]: No, StackOverflow is the only way to get free support. If you have an urgent need for support, you can consider paid support by Marmelab.

Comment (paulito415) [reply packages/ra-core/src/form/FormDataConsumer.js]: OK thanks Francois! I was able to solve m problem by entirely restructuring my code / layout.
