### PR TITLE
Fix `SimpleFormIterator` defaultValues when adding a record

### LINKED ISSUE #8178: Array input issue when removing and reinserting element
# Bug
The bug happens when I have inside a `SimpleFormIterator` a `React.FC` or a `FormDataConsumer`.
In those cases if I have defaults they are not applied and if there is a record the informations shown does not respect the form state.

# To reproduce
To reproduce the bug use this [CODESANDBOX](https://codesandbox.io/s/heuristic-diffie-gzwqfp?file=/src/comments/CommentEdit.tsx)
Enter into the edit of the only comment present here delete this from the form. Then reinsert it. 
The form seems filled because you can see the numbers but if you press submit the validation error appears informing you that the form is not filled.

Result of bug:
image

# Problem found
The screen below is the `SimpleFormIterator` `addField` function, in this function if I have a form data consumer or any other React.FC that have not source nor the default value on the SimpleFormIterator level the default returned is `{undefined: ""}`
This causes that react admin renders the array value from the record thinking that the form is filling with the record, showing a wrong value from record and not from the form state. 
image

# Drity workaround to partially solve this issue

```tsx
type Props<T> = SimpleFormIteratorProps & {
  defaultValue?: { [TKey in keyof T]: T[TKey] }
}

/**
 * This component is used because react admin cannot handle default values for React.FC children of
 * the standard SimpleFormIterator. For those elements the native one takes the default from the record but it
 * does not update the record with like result having the field filled but with an empty form.
 *
 * @param SimpleFormIteratorProps all the props of the SimpleFormIterator
 * @param defaultValue this one is used when a new element is added
 * @return the standard SimpleFormIterator with the ability to add a default value to each element of the array
 */
const KSimpleFormIterator = <T extends any>({
  children,
  source,
  defaultValue,
  ...rest
}: Props<T>) => {
  // this source is automatically passed by the array input
  if (!source) throw new Error('KSimpleFormIterator: source is required')

  // we are going to perform a watch on the the array input values
  const arrayValue = useWatch({ name: source }) as Array<any>

  // we memorize the array input values
  const [value, setValue] = useState(arrayValue)

  // this hook is used to manipulate the ReactAdmin array input form state
  const { append, remove } = useArrayInput({ ...rest })

  console.log('aaa', {
    children: Children.toArray(children),
  })

  // if an element was added
  if (value.length < arrayValue.length) {
    // remove the last added element with wrong default value
    remove(arrayValue.length - 1)
    // set the default value with the correct one appending it like last element of the array
    append(defaultValue)
    // updates the cached value inside the component
    setValue(arrayValue)
  } else if (value.length > arrayValue.length) {
    // updates the cached value inside the component
    setValue(arrayValue)
  }

  return (
    <SimpleFormIterator {...rest} source={source}>
      {children}
    </SimpleFormIterator>
  )
}

export default KSimpleFormIterator

```

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #8178

### CODE REVIEW

**Review by thibault-barrat — APPROVED** [review]

File: packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx [hunk 1]
```diff
@@ -30,6 +30,8 @@ import { AddItemButton as DefaultAddItemButton } from './AddItemButton';
 import { RemoveItemButton as DefaultRemoveItemButton } from './RemoveItemButton';
 import { ReOrderButtons as DefaultReOrderButtons } from './ReOrderButtons';
 
+let initialDefaultValue = {};
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx:33]: I'm very scared of that type of global values - it will persist across the entire app. We'll see side effects in tests. 

Can't you find an alternative fix that doesn't rely on a global? Why not a `ref`?

File: packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx [hunk 2]
```diff
@@ -57,13 +59,22 @@ export const SimpleFormIterator = (props: SimpleFormIteratorProps) => {
...
+
     const addField = useCallback(
         (item: any = undefined) => {
             let defaultValue = item;
             if (item == null) {
+                defaultValue = initialDefaultValue;
                 if (
                     Children.count(children) === 1 &&
                     React.isValidElement(Children.only(children)) &&
+                    (Children.only(children) as ReactElement<any>).type !==
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx:76]: Can we avoid inspecting the child type?

**Review by fzaninotto — CHANGES_REQUESTED** [review]

File: packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx (hunk 2 above)
Comment (WiXSL) [reply packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx]: Actually, I just realized that check is not necessary there at all

**Review by slax57 — APPROVED** [review]

**Comment by fzaninotto** [comment]
Actually, this PR misses a unit test...
