### PR TITLE
[RFR] Fix Select inputs validation

### LINKED ISSUE #2142: SelectInput and SelectArrayInput meta
**What you were expecting:**
When I select my input, if there is an error, the error would be displayed.

**What happened instead:**
The touched meta is always false. So the error is not displayed.
If I submit, the error is displayed but in black color (for the SelectArrayInput)=> When I see on MaterialUi, I suppose the FormControl need the "error" attribute.

```jsx
<FormControl className={classes.formControl} error>
          <InputLabel htmlFor="name-error">Name</InputLabel>
          <Select
            value={this.state.name}
            onChange={this.handleChange}
            name="name"
            renderValue={value => `⚠️  - ${value}`}
            input={<Input id="name-error" />}
          >
            <MenuItem value="">
              <em>None</em>
            </MenuItem>
            <MenuItem value="hai">Hai</MenuItem>
            <MenuItem value="olivier">Olivier</MenuItem>
            <MenuItem value="kevin">Kevin</MenuItem>
          </Select>
          <FormHelperText>Error</FormHelperText>
        </FormControl>
```

**Steps to reproduce:**
For SelectInput, add the required() validator, click and unclick.

For SelectArrayInput , create a valitor : 
```jsx
export const requiredSelectArrayInput = memoize((message = 'ra.validation.required') =>
    Object.assign(
        (value, values, props) =>
            !isEmpty(value) && value.length > 0 ? undefined : getMessage(message, undefined, value, values, props),
        { isRequired: true }
    )
);
```

**Environment**

* React-admin version: 2.2.0
* Last version that did not exhibit the issue (if applicable):
* React version:16.3
* Browser: Chrome
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by djhi**
Fix #2142

### CODE REVIEW

File: packages/ra-ui-materialui/src/input/SelectArrayInput.js [hunk 1]
```diff
@@ -135,6 +135,8 @@ export class SelectArrayInput extends Component {
     }
 
     handleChange = event => {
+        this.props.input.onChange(event.target.value);
```
Comment (Kmaschta) [inline packages/ra-ui-materialui/src/input/SelectArrayInput.js]: This is `onChange` not `onBlur`. Hm?

File: packages/ra-ui-materialui/src/input/SelectInput.js [hunk 2]
```diff
@@ -187,7 +190,9 @@ export class SelectInput extends Component {
             );
         }
         const { touched, error, helperText = false } = meta;
+        const helperTextError = (touched && error) || helperText;
 
+        console.log({ meta, helperTextError });
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/SelectInput.js]: `console.log()` spotted
