### PR TITLE
Fix list actions don't trigger a refetch

### LINKED ISSUE #7494: React 18 strict mode breaks URL query params
**What you were expecting:**

That react admin works normally with React 18 strict mode

**What happened instead:**

When I click on a column header to sort the url doesn't update with query params, so nothing happens.

**Steps to reproduce:**

In the code sandbox try to sort a column, see it doesn't work. In index.js, comment out the React 18 section and uncomment the React 17 mode section, sorting should work now. 

**Related code:**

https://codesandbox.io/s/sweet-fast-1pkgk5?file=/src/index.js

React 18 mode (broken):

```
import App from "./App";
import * as React from "react";
import { StrictMode } from "react";
import * as ReactDOMClient from "react-dom/client";

const rootElement = document.getElementById("root");
const root = ReactDOMClient.createRoot(rootElement);

root.render(
  <StrictMode>
    <App />
  </StrictMode>
);
```

React 17 mode (working):

```
import App from "./App";
import * as React from "react";
import { render } from "react-dom";
const container = document.getElementById("root");
render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  container
);
```

**Environment**

* React-admin version: 4
* React version: 18
* Browser: Latest Chrome and Safari

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #7494

### CODE REVIEW

File: packages/ra-core/src/util/hooks.ts [hunk 1]
```diff
@@ -73,6 +73,7 @@ export function useTimeout(ms = 0, key = '') {
 export function useIsMounted() {
     const isMounted = useRef(true);
```
Comment (WiXSL) [inline packages/ra-core/src/util/hooks.ts:74]: Shouldn't be initialized with `false` ?

**Review by WiXSL — CHANGES_REQUESTED** [review]

File: packages/ra-core/src/util/hooks.ts (hunk 1 above)
Comment (WiXSL) [inline packages/ra-core/src/util/hooks.ts:74]: Shouldn't be initialized with `false` ?

**Review by WiXSL — CHANGES_REQUESTED** [review]

File: packages/ra-core/src/util/hooks.ts (hunk 1 above)
Comment (fzaninotto) [reply packages/ra-core/src/util/hooks.ts:74]: No, as it would trigger a useless re-render

**Review by WiXSL — APPROVED** [review]

**Review by djhi — APPROVED** [review]
