### PR TITLE
Fix validation errors from resolvers are not translated

### LINKED ISSUE #9084: String error messages are not translated when using global validation
**What you were expecting:**

When rendering InputHelperText with props: 
```
{
error: 'my.translation.key'
touched: true
}
```
Then error message should be translated

**What happened instead:**

They are not translated (because translate() is not called in the component InputHelperText)

**Steps to reproduce:**

Use yupResolver(<schema>) as resolver in a Form component. Error message displayed in the InputHelperText should be translated, but they are not. Instead the translation key is displayed.

In the sandbox below: 
1 - In the form fill the field 'body' and let field 'post' empty. 
2 - Validate the form
3 - The error displayed in the helper text is not translated (the same key is translated and displayed juste above the form)

**Related code:**

https://stackblitz.com/edit/github-jywgwp?file=src%2Findex.tsx

**Other information:**
**Solution**
change the following in 'packages/ra-ui-materialui/src/input/InputHelperText.tsx' line 14

Change
```
    if (touched && error) {
        if ((error as ValidationErrorMessageWithArgs).message) {
            return <ValidationError error={error} />;
        }
        return <>{error}</>;
    }
```

Into
```
    if (touched && error) {
        if ((error as ValidationErrorMessageWithArgs).message) {
            return <ValidationError error={error} />;
        }
        return <>{translate(error)}</>;
    }
```

**Environment**

* React-admin version: 4.12
* Last version that did not exhibit the issue (if applicable): was working on 4.4 
* React version: 18.2
* Browser: all
* Stack trace (in case of a JS error): no error

### PR DESCRIPTION
**Pull request by djhi**
Fixes #9084

### CODE REVIEW

File: packages/ra-core/src/form/ValidationError.tsx [hunk 1]
```diff
@@ -11,13 +11,26 @@ export interface ValidationErrorProps {
...
-    if ((error as ValidationErrorMessageWithArgs).message) {
-        const { message, args } = error as ValidationErrorMessageWithArgs;
+    // react-hook-form expects errors to be plain strings but our validators can return objects
+    // that have message and args.
+    // To avoid double translation for users that validate with a schema instead of our validators
+    // we use a special format for our validators errors.
+    // The ValidationError component will check for this format and extract the message and args
+    // to translate.
+    if (typeof error === 'string' && error.startsWith('@@react-admin@@')) {
+        errorMessage = JSON.parse(error.replace('@@react-admin@@', ''));
```
Comment (fzaninotto) [inline packages/ra-core/src/form/ValidationError.tsx:23]: the error message may contain the string '@@react-admin@@' (because, why not?). Instead of a replace, I'd use a substring for improved robustness.

File: packages/ra-core/src/form/Form.stories.tsx [hunk 2]
```diff
@@ -164,3 +166,25 @@ export const UndefinedValue = () => {
...
+    const [result, setResult] = React.useState<any>();
+    return (
+        <CoreAdminContext>
+            <Form
+                record={{}}
+                onSubmit={data => setResult(data)}
+                resolver={zodResolver(zodSchema)}
+            >
+                <Input source="preTranslated" />
+                <Input source="translationKey" />
```
Comment (fzaninotto) [inline packages/ra-core/src/form/Form.stories.tsx:184]: it's not entirely clear what to expect here. Would you mind adding a description?

**Review by fzaninotto — CHANGES_REQUESTED** [review]
This PR is missing some additional tests. Also, as this changes the behavior of the resolvers validation, I'd be more comfortable if this was released in a minor version. Would you mind targeting the `next` branch instead?

File: packages/ra-core/src/form/useInput.ts [hunk 3]
```diff
@@ -43,7 +42,6 @@ export const useInput = <ValueType = any>(
     const formGroupName = useFormGroupContext();
     const formGroups = useFormGroups();
     const record = useRecordContext();
-    const getValidationErrorMessage = useGetValidationErrorMessage();
```
[the remark this answers is not in the document]
Comment (djhi) [reply packages/ra-core/src/form/useInput.ts:46]: Added

**Review by fzaninotto — COMMENTED** [review]
Cool, but we really need extensive tests showing that error message translation occurs once and only once in the 3 following cases:

- per input validation
- form-wide validation with `validate`
- form-wide validation with `resolvers`

These tests may be scattered around several components, I'm not sure. A central test for this matter would be welcome.

**Comment by djhi** [comment]
> 

Added to `Form.spec.tsx`

File: packages/ra-core/src/form/ValidationError.tsx [hunk 4]
```diff
@@ -32,10 +32,10 @@ const ValidationError = (props: ValidationErrorProps) => {
             message,
             args,
         } = errorMessage as ValidationErrorMessageWithArgs;
-        return <>{translate(message, { _: message, ...args })}</>;
+        return <>{translate(message, args)}</>;
     }
 
-    return <>{translate(errorMessage as string, { _: errorMessage })}</>;
+    return <>{translate(errorMessage as string)}</>;
```
Comment (fzaninotto) [inline packages/ra-core/src/form/ValidationError.tsx:38]: Why did you remove that?

**Review by fzaninotto — CHANGES_REQUESTED** [review]

File: packages/ra-core/src/form/ValidationError.tsx (hunk 4 above)
Comment (djhi) [reply packages/ra-core/src/form/ValidationError.tsx]: To allow warnings on missing translations

File: packages/ra-core/src/form/ValidationError.tsx [hunk 5]
```diff
@@ -32,6 +32,7 @@ const ValidationError = (props: ValidationErrorProps) => {
             message,
             args,
         } = errorMessage as ValidationErrorMessageWithArgs;
+        console.log({ message, args });
```
Comment (fzaninotto) [inline packages/ra-core/src/form/ValidationError.tsx:35]: console.log spotted

**Review by fzaninotto — CHANGES_REQUESTED** [review]

File: packages/ra-core/src/form/ValidationError.tsx (hunk 4 above)
Comment (fzaninotto) [reply packages/ra-core/src/form/ValidationError.tsx]: But then it's a regression, as missing translation warnings will now get logged in the console while they  were not in `master`. 

If this is only for the purpose of tests, you can enable warning on missing message in the parameters of the polyglotI18nProvider options (https://airbnb.io/polyglot.js/#options-overview). And if it doesn't work, you'll have to use a spy i18nProvider.

Comment (djhi) [reply packages/ra-core/src/form/ValidationError.tsx]: The fact that it silenced the missing translations warnings was actually a reggresion and was contradictory to the expected and documented behavior.

File: packages/ra-core/src/form/Form.spec.tsx [hunk 6]
```diff
@@ -17,6 +19,8 @@ import {
     SanitizeEmptyValues,
     NullValue,
 } from './Form.stories';
+import { mergeTranslations } from '../i18n';
+import { de } from 'date-fns/locale';
```
Comment (fzaninotto) [inline packages/ra-core/src/form/Form.spec.tsx:23]: linter warning

File: packages/ra-core/src/form/Form.spec.tsx [hunk 7]
```diff
@@ -4,14 +4,23 @@ import { useFormState, useFormContext } from 'react-hook-form';
...
-import { NullValue } from './Form.stories';
+import {
+    FormLevelValidation,
+    InputLevelValidation,
+    ZodResolver,
+    SanitizeEmptyValues,
+    NullValue,
+} from './Form.stories';
+import { mergeTranslations } from '../i18n';
+import { de } from 'date-fns/locale';
```
Comment (djhi) [inline packages/ra-core/src/form/Form.spec.tsx:23]:
```suggestion
```

**Review by fzaninotto — APPROVED** [review]
