### PR TITLE
Fix withLifecycleCallbacks types

### LINKED ISSUE #9152: Return type of ResourceCallbacks.beforeSave should be Promise<Partial<T>>
The return type of `ResourceCallbacks.beforeSave` should be the same as the type of the parameter `data`. The function cannot create a `RaRecord` from a `Partial<RaRecord>`.

https://github.com/marmelab/react-admin/blob/de8fbaa3285714aab914e0e76cc369c09a817d3c/packages/ra-core/src/dataProvider/withLifecycleCallbacks.ts#L577C73-L577C74

### PR DESCRIPTION
**Pull request by djhi**
Supersedes #9156
Fixes #9152

### CODE REVIEW

File: packages/ra-core/src/dataProvider/withLifecycleCallbacks.ts [hunk 1]
```diff
@@ -332,7 +332,7 @@ export const withLifecycleCallbacks = (
 
         create: async function <RecordType extends RaRecord = any>(
             resource: string,
-            params: CreateParams<RecordType>
+            params: CreateParams<Partial<RecordType>>
```
Comment (fzaninotto) [inline packages/ra-core/src/dataProvider/withLifecycleCallbacks.ts:335]: I don't think this should be changed - to me, it's the CreateParams and UpdatePArams that should be changed. 

```diff
export interface CreateParams<T = any> {
-   data: T;
+   data: Partial<T>;
    meta?: any;
}
```

Comment (djhi) [reply packages/ra-core/src/dataProvider/withLifecycleCallbacks.ts]: Agreed and done

**Review by slax57 — APPROVED** [review]
