### PR TITLE
[RFR] New AutocompleteInput using Downshift

### LINKED ISSUE #3519: Reimplement AutocompleteInput and AutocompleteArrayInput using downshift
The V3 Roadmap (#3194) include a rewrite of `<AutocompleteInput>` and `<AutocompleteArrayInput>` using  `downshift`.

Here is the current PR implementation: #3031 

This issue purpose is to list all problems the new implementation should fix:

- #2961 The suggestion list is wrongly placed when a second search as few results
- #2428 The suggestion list appears again after a suggestion is selected
- #3098 The `<AutocompleteInput>` doesn't work in a `<ReferenceInput>`
- #3148 The selected value is always the first suggested item (even if it shouldn't)

### PR DESCRIPTION
**Pull request by ThieryMichel**
Fixes #3519, #2428

- [x] Implementation
- [x] Tests
- [x] Upgrade Guide
- [x] Documentation

### CODE REVIEW

**Comment by Kmaschta** [comment]
Be aware that there is an open issue with this component, it would be awesome if this PR might help. https://github.com/marmelab/react-admin/issues/2428

**Comment by fzaninotto** [comment]
This may be an improvement, but it's also a BC break, since additional props were passed to react-autosuggest. This can't be merged before 3.0.

**Comment by komik966** [comment]
This autocomplete looks cleaner :) I tried it but this problem: https://github.com/mui-org/material-ui/issues/13179 still remains.

This improvement not affects much code of ra - maybe it's possible to add it as new Autocomplete and deprecate actual one before v3 release? or publish it as package (e.g. https://github.com/fizix-io/ra-customizable-datagrid)?

File: examples/simple/src/posts/PostEdit.js [hunk 1]
```diff
@@ -65,6 +68,49 @@ const PostEdit = props => (
...
                 </ImageInput>
+                {permissions === 'admin' && (
+                    <ArrayInput source="authors">
+                        <SimpleFormIterator>
+                            <ReferenceInput
+                                label="User"
+                                source="user_id"
+                                reference="users"
+                            >
+                                <AutocompleteInput />
```
Comment (fzaninotto) [inline examples/simple/src/posts/PostEdit.js]: an `ArrayInput` listing `AutocompleteInput`?? Why didn't you use an `AutocompleteArrayInput`?

File: packages/ra-ui-materialui/src/input/AutocompleteInput/getSuggestions.spec.js [hunk 2]
```diff
@@ -0,0 +1,83 @@
+import getSuggestions from './getSuggestions';
+
+describe('getSuggestions', () => {
+    const choices = [
+        { id: 1, value: 'one' },
+        { id: 2, value: 'two' },
+        { id: 3, value: 'three' },
+    ];
+
+    it('should return suggestions based on choices', () => {
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput/getSuggestions.spec.js]:
```suggestion
    it('should return all suggestions when filtered by empty string', () => {
```

File: packages/ra-ui-materialui/src/input/AutocompleteInput/getSuggestions.spec.js [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+                allowEmpty: false,
+                optionText: 'value',
+                getSuggestionText: ({ value }) => value,
+                optionValue: 'id',
+                limitChoicesToValue: true,
+            })('**o')
+        ).toEqual([{ id: 1, value: '**one' }]);
+    });
+
+    it('should not filter choices based on second argument if limitChoicesToValue is false', () => {
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput/getSuggestions.spec.js]: I don't understand this one

File: packages/ra-ui-materialui/src/input/AutocompleteInput/index.js [hunk 4]
```diff
@@ -0,0 +1,396 @@
...
+ * <AutocompleteInput source="author_id" options={{ fullWidth: true }} />
+ */
+const AutocompleteInput = ({
+    classes: classesOverride,
+    allowEmpty,
+    choices,
+    fullWidth,
+    helperText,
+    label,
+    limitChoicesToValue,
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput/index.js]: this one isn't documented and I don't know what it means

File: cypress/integration/edit.js [hunk 5]
```diff
@@ -88,9 +88,6 @@ describe('Edit Page', () => {
             .clear()
             .type('Sed quo');
         cy.get('[role="tooltip"]').within(() => {
-            cy.contains(
```
Comment (fzaninotto) [inline cypress/integration/edit.js]: this is a regression

File: packages/ra-ui-materialui/src/input/AutocompleteInput/index.js [hunk 6]
```diff
@@ -0,0 +1,396 @@
...
+            if (setFilter) {
+                setFilter(value);
+            }
+        },
+        [setFilter]
+    );
+
+    useEffect(() => {
+        updateFilter('');
+    }, [input.value, updateFilter]);
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput/index.js]: I don't understand this one. Each time the value changes, the filter resets? Why? A JsDoc comment would be welcome

File: packages/ra-ui-materialui/src/input/AutocompleteInput/index.js [hunk 7]
```diff
@@ -0,0 +1,396 @@
...
+
+    const getSuggestionTextFromValue = value => {
+        const currentChoice = choices.find(
+            choice => getSuggestionValue(choice) === value
+        );
+
+        return getSuggestionText(currentChoice);
+    };
+
+    const handleSuggestionSelected = suggestionText => {
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput/index.js]: needs memoization with `useCallback`, just like most of the functions defined in this component

Comment (fzaninotto) [inline packages/ra-ui-materialui/src/input/AutocompleteInput/index.js]: I'm not comfortable with using the text to find the suggestion. In the previous version, this handler received the suggestion *object*, so there was no need to search for it. 

I'm thinking about cases where multiple suggestions may have the same suggestion text.

File: packages/ra-ui-materialui/src/input/AutocompleteInput/getSuggestions.spec.js (hunk 3 above)
Comment (djhi) [reply packages/ra-ui-materialui/src/input/AutocompleteInput/getSuggestions.spec.js]: I suspect a regression here

File: packages/ra-ui-materialui/src/input/AutocompleteInput/index.js (hunk 4 above)
Comment (djhi) [reply packages/ra-ui-materialui/src/input/AutocompleteInput/index.js]: It is in the current version: https://marmelab.com/react-admin/Inputs.html#autocompleteinput

> If you want to limit the initial choices shown to the current value only, you can set the limitChoicesToValue prop.

File: cypress/integration/edit.js (hunk 5 above)
Comment (djhi) [reply cypress/integration/edit.js]: Yes, we talked about it and you said ok for it

File: examples/simple/src/posts/PostEdit.js (hunk 1 above)
Comment (djhi) [reply examples/simple/src/posts/PostEdit.js]: Because this is not the only field inside this `ArrayInput`. See the `Role` field below. However, I believe this was introduced as a way to manually test the `AutoCompleteInput` by @ThieryMichel and is not used in any automated tests. Maybe we can remove it ?

File: packages/ra-ui-materialui/src/input/AutocompleteInput/index.js (hunk 7 above)
Comment (djhi) [reply packages/ra-ui-materialui/src/input/AutocompleteInput/index.js]: Good catch. Fixed

File: packages/ra-ui-materialui/src/input/AutocompleteInput/index.js (hunk 6 above)
Comment (djhi) [reply packages/ra-ui-materialui/src/input/AutocompleteInput/index.js]: I added a comment about it

**Comment by fzaninotto** [comment]
Argh! needs rebase.

File: packages/ra-ui-materialui/src/input/AutocompleteInput/getSuggestions.spec.js (hunk 3 above)
Comment (djhi) [reply packages/ra-ui-materialui/src/input/AutocompleteInput/getSuggestions.spec.js]: Fixed

File: cypress/integration/edit.js (hunk 5 above)
Comment (fzaninotto) [reply cypress/integration/edit.js]: Gotcha

File: examples/simple/src/posts/PostEdit.js (hunk 1 above)
Comment (fzaninotto) [reply examples/simple/src/posts/PostEdit.js]: we may remove it in the future, let's keep it for now

File: packages/ra-ui-materialui/package.json [hunk 8]
```diff
@@ -49,6 +49,7 @@
         "classnames": "~2.2.5",
         "connected-react-router": "^6.4.0",
         "css-mediaquery": "^0.1.2",
+        "downshift": "3.2.7",
```
Comment (fzaninotto) [inline packages/ra-ui-materialui/package.json]: `react-autosuggest` isn't removed because we still have AutocompletearrayInput, right?

Comment (djhi) [reply packages/ra-ui-materialui/package.json]: Yes, we'll have to rewrite this component too
